# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtarmsim/ui/mainwindow.ui'
#
# Created: Thu Nov  2 18:25:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 716)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("QtARMSim")
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetCode = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetCode.setMinimumSize(QtCore.QSize(400, 300))
        self.tabWidgetCode.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidgetCode.setObjectName("tabWidgetCode")
        self.tabSource = QtGui.QWidget()
        self.tabSource.setObjectName("tabSource")
        self.verticalLayoutSource = QtGui.QVBoxLayout(self.tabSource)
        self.verticalLayoutSource.setObjectName("verticalLayoutSource")
        self.tabWidgetCode.addTab(self.tabSource, "")
        self.tabARMSim = QtGui.QWidget()
        self.tabARMSim.setAccessibleName("")
        self.tabARMSim.setObjectName("tabARMSim")
        self.verticalLayoutARMSim = QtGui.QVBoxLayout(self.tabARMSim)
        self.verticalLayoutARMSim.setObjectName("verticalLayoutARMSim")
        self.tabWidgetCode.addTab(self.tabARMSim, "")
        self.verticalLayout.addWidget(self.tabWidgetCode)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetRegisters = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetRegisters.sizePolicy().hasHeightForWidth())
        self.dockWidgetRegisters.setSizePolicy(sizePolicy)
        self.dockWidgetRegisters.setMinimumSize(QtCore.QSize(180, 100))
        self.dockWidgetRegisters.setToolTip("")
        self.dockWidgetRegisters.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetRegisters.setObjectName("dockWidgetRegisters")
        self.dockWidgetContentsRegisters = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContentsRegisters.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsRegisters.setSizePolicy(sizePolicy)
        self.dockWidgetContentsRegisters.setObjectName("dockWidgetContentsRegisters")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContentsRegisters)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.treeViewRegisters = MyQTreeView(self.dockWidgetContentsRegisters)
        self.treeViewRegisters.setEnabled(True)
        self.treeViewRegisters.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeViewRegisters.setFrameShadow(QtGui.QFrame.Plain)
        self.treeViewRegisters.setLineWidth(0)
        self.treeViewRegisters.setAlternatingRowColors(True)
        self.treeViewRegisters.setObjectName("treeViewRegisters")
        self.verticalLayout_6.addWidget(self.treeViewRegisters)
        self.dockWidgetRegisters.setWidget(self.dockWidgetContentsRegisters)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetRegisters)
        self.dockWidgetMemory = QtGui.QDockWidget(MainWindow)
        self.dockWidgetMemory.setMinimumSize(QtCore.QSize(180, 100))
        self.dockWidgetMemory.setToolTip("")
        self.dockWidgetMemory.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetMemory.setObjectName("dockWidgetMemory")
        self.dockWidgetContentsMemory = QtGui.QWidget()
        self.dockWidgetContentsMemory.setObjectName("dockWidgetContentsMemory")
        self.dockWidgetMemoryLayout = QtGui.QVBoxLayout(self.dockWidgetContentsMemory)
        self.dockWidgetMemoryLayout.setObjectName("dockWidgetMemoryLayout")
        self.treeViewMemory = MyQTreeView(self.dockWidgetContentsMemory)
        self.treeViewMemory.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeViewMemory.setFrameShadow(QtGui.QFrame.Plain)
        self.treeViewMemory.setLineWidth(0)
        self.treeViewMemory.setAlternatingRowColors(True)
        self.treeViewMemory.setObjectName("treeViewMemory")
        self.dockWidgetMemoryLayout.addWidget(self.treeViewMemory)
        self.dockWidgetMemory.setWidget(self.dockWidgetContentsMemory)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetMemory)
        self.dockWidgetMessages = QtGui.QDockWidget(MainWindow)
        self.dockWidgetMessages.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidgetMessages.setObjectName("dockWidgetMessages")
        self.dockWidgetMessagesContents = QtGui.QWidget()
        self.dockWidgetMessagesContents.setObjectName("dockWidgetMessagesContents")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetMessagesContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEditMessages = QtGui.QTextEdit(self.dockWidgetMessagesContents)
        self.textEditMessages.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditMessages.sizePolicy().hasHeightForWidth())
        self.textEditMessages.setSizePolicy(sizePolicy)
        self.textEditMessages.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditMessages.setWhatsThis("")
        self.textEditMessages.setDocumentTitle("")
        self.textEditMessages.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditMessages.setObjectName("textEditMessages")
        self.verticalLayout_5.addWidget(self.textEditMessages)
        self.dockWidgetMessages.setWidget(self.dockWidgetMessagesContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMessages)
        self.dockWidgetMemoryDump = QtGui.QDockWidget(MainWindow)
        self.dockWidgetMemoryDump.setObjectName("dockWidgetMemoryDump")
        self.dockWidgetMemoryDumpContents = QtGui.QWidget()
        self.dockWidgetMemoryDumpContents.setObjectName("dockWidgetMemoryDumpContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetMemoryDumpContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidgetMemoryDump = QtGui.QTabWidget(self.dockWidgetMemoryDumpContents)
        self.tabWidgetMemoryDump.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidgetMemoryDump.setObjectName("tabWidgetMemoryDump")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidgetMemoryDump.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidgetMemoryDump.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidgetMemoryDump)
        self.dockWidgetMemoryDump.setWidget(self.dockWidgetMemoryDumpContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMemoryDump)
        self.dockWidgetLCDDisplay = QtGui.QDockWidget(MainWindow)
        self.dockWidgetLCDDisplay.setObjectName("dockWidgetLCDDisplay")
        self.dockWidgetLCDContents = QtGui.QWidget()
        self.dockWidgetLCDContents.setObjectName("dockWidgetLCDContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetLCDContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.memoryLCDView = MemoryLCDView(self.dockWidgetLCDContents)
        self.memoryLCDView.setObjectName("memoryLCDView")
        self.horizontalLayout.addWidget(self.memoryLCDView)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.dockWidgetLCDDisplay.setWidget(self.dockWidgetLCDContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetLCDDisplay)
        self.actionWhats_This = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":themes/breeze/32/help-whatsthis.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionWhats_This.setIcon(icon)
        self.actionWhats_This.setObjectName("actionWhats_This")
        self.actionAbout_Qt_ARMSim = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":themes/breeze/32/help-about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout_Qt_ARMSim.setIcon(icon1)
        self.actionAbout_Qt_ARMSim.setObjectName("actionAbout_Qt_ARMSim")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":themes/breeze/22/help-contents.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_ARMSim = QtGui.QAction(MainWindow)
        self.actionAbout_ARMSim.setIcon(icon1)
        self.actionAbout_ARMSim.setObjectName("actionAbout_ARMSim")
        self.actionNew = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionNew.setIcon(icon3)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave_As.setIcon(icon6)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":themes/breeze/32/document-print.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setObjectName("actionPrint")
        self.actionQuit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":themes/breeze/32/application-exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionQuit.setIcon(icon8)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset_Registers = QtGui.QAction(MainWindow)
        self.actionReset_Registers.setObjectName("actionReset_Registers")
        self.actionReset_Memory = QtGui.QAction(MainWindow)
        self.actionReset_Memory.setObjectName("actionReset_Memory")
        self.actionClear_Console = QtGui.QAction(MainWindow)
        self.actionClear_Console.setObjectName("actionClear_Console")
        self.actionRun = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":themes/breeze/24/system-run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRun.setIcon(icon9)
        self.actionRun.setObjectName("actionRun")
        self.actionStepInto = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":themes/breeze/24/debug-step-into.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStepInto.setIcon(icon10)
        self.actionStepInto.setObjectName("actionStepInto")
        self.actionBreakpoints = QtGui.QAction(MainWindow)
        self.actionBreakpoints.setObjectName("actionBreakpoints")
        self.actionShow_Statusbar = QtGui.QAction(MainWindow)
        self.actionShow_Statusbar.setCheckable(True)
        self.actionShow_Statusbar.setChecked(True)
        self.actionShow_Statusbar.setObjectName("actionShow_Statusbar")
        self.actionShow_Toolbar = QtGui.QAction(MainWindow)
        self.actionShow_Toolbar.setCheckable(True)
        self.actionShow_Toolbar.setChecked(True)
        self.actionShow_Toolbar.setObjectName("actionShow_Toolbar")
        self.actionShow_Registers = QtGui.QAction(MainWindow)
        self.actionShow_Registers.setCheckable(True)
        self.actionShow_Registers.setChecked(True)
        self.actionShow_Registers.setObjectName("actionShow_Registers")
        self.actionShow_Memory = QtGui.QAction(MainWindow)
        self.actionShow_Memory.setCheckable(True)
        self.actionShow_Memory.setChecked(True)
        self.actionShow_Memory.setObjectName("actionShow_Memory")
        self.actionRestore_Default_Layout = QtGui.QAction(MainWindow)
        self.actionRestore_Default_Layout.setObjectName("actionRestore_Default_Layout")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.action_Undo = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":themes/breeze/32/edit-undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Undo.setIcon(icon11)
        self.action_Undo.setObjectName("action_Undo")
        self.actionRedo = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":themes/breeze/32/edit-redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRedo.setIcon(icon12)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-cut.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCut.setIcon(icon13)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon14.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopy.setIcon(icon14)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPaste.setIcon(icon15)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSelect_All = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":themes/breeze/24/edit-select-all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelect_All.setIcon(icon16)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionShow_Messages = QtGui.QAction(MainWindow)
        self.actionShow_Messages.setCheckable(True)
        self.actionShow_Messages.setChecked(True)
        self.actionShow_Messages.setObjectName("actionShow_Messages")
        self.actionStepOver = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(":themes/breeze/24/debug-step-over.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStepOver.setIcon(icon17)
        self.actionStepOver.setObjectName("actionStepOver")
        self.actionRestart = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(":themes/breeze/32/view-refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRestart.setIcon(icon18)
        self.actionRestart.setObjectName("actionRestart")
        self.actionResume = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon19.addPixmap(QtGui.QPixmap(":themes/breeze/24/debug-run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionResume.setIcon(icon19)
        self.actionResume.setObjectName("actionResume")
        self.actionShow_Memory_Dump = QtGui.QAction(MainWindow)
        self.actionShow_Memory_Dump.setCheckable(True)
        self.actionShow_Memory_Dump.setObjectName("actionShow_Memory_Dump")
        self.actionShow_LCD_Display = QtGui.QAction(MainWindow)
        self.actionShow_LCD_Display.setCheckable(True)
        self.actionShow_LCD_Display.setObjectName("actionShow_LCD_Display")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStepInto)
        self.menuRun.addAction(self.actionStepOver)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRestart)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionBreakpoints)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionReset_Registers)
        self.menuRun.addAction(self.actionReset_Memory)
        self.menuRun.addAction(self.actionClear_Console)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionWhats_This)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Qt_ARMSim)
        self.menuHelp.addAction(self.actionAbout_ARMSim)
        self.menu_Window.addAction(self.actionShow_Statusbar)
        self.menu_Window.addAction(self.actionShow_Toolbar)
        self.menu_Window.addAction(self.actionShow_Registers)
        self.menu_Window.addAction(self.actionShow_Memory)
        self.menu_Window.addAction(self.actionShow_Messages)
        self.menu_Window.addAction(self.actionShow_Memory_Dump)
        self.menu_Window.addAction(self.actionShow_LCD_Display)
        self.menu_Window.addSeparator()
        self.menu_Window.addAction(self.actionRestore_Default_Layout)
        self.menu_Window.addSeparator()
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.actionRedo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionCut)
        self.menu_Edit.addAction(self.actionCopy)
        self.menu_Edit.addAction(self.actionPaste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStepInto)
        self.toolBar.addAction(self.actionStepOver)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRestart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionWhats_This)

        self.retranslateUi(MainWindow)
        self.tabWidgetCode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabSource.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The Source Code tab is used to edit the assembler source code that is going to be simmulated", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetCode.setTabText(self.tabWidgetCode.indexOf(self.tabSource), QtGui.QApplication.translate("MainWindow", "Source Code", None, QtGui.QApplication.UnicodeUTF8))
        self.tabARMSim.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The ArmSim tab is used to inspect and simmulate the ARM machine code generated after assembling the source code", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetCode.setTabText(self.tabWidgetCode.indexOf(self.tabARMSim), QtGui.QApplication.translate("MainWindow", "ARMSim", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "&Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Barra de herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetRegisters.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The Registers dock shows the contents of the registers", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetRegisters.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMemory.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The Memory dock shows the contents of the memory", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMemory.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMessages.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The Messages dock shows QtARMSim and ARMSim messages", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMessages.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMemoryDump.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The Memory Dump dock shows the memory dump of the simulated system", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMemoryDump.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Memory Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMemoryDump.setTabText(self.tabWidgetMemoryDump.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMemoryDump.setTabText(self.tabWidgetMemoryDump.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetLCDDisplay.setWhatsThis(QtGui.QApplication.translate("MainWindow", "The LCD Display shows the output of a simulated LCD Display Device", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetLCDDisplay.setWindowTitle(QtGui.QApplication.translate("MainWindow", "LCD Display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhats_This.setText(QtGui.QApplication.translate("MainWindow", "What\'s &This?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhats_This.setStatusTip(QtGui.QApplication.translate("MainWindow", "¿Qué es esto?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhats_This.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Activa la ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWhats_This.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt_ARMSim.setText(QtGui.QApplication.translate("MainWindow", "About QtARMSim", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt_ARMSim.setStatusTip(QtGui.QApplication.translate("MainWindow", "Sobre spim", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt_ARMSim.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Imprime en el panel mensajes información sobre XSPIM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "QtARMSim &Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_ARMSim.setText(QtGui.QApplication.translate("MainWindow", "About ARMSim", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open ARM assembler file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "&Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Registers.setText(QtGui.QApplication.translate("MainWindow", "Reset R&egisters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Memory.setText(QtGui.QApplication.translate("MainWindow", "Reset &Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Console.setText(QtGui.QApplication.translate("MainWindow", "Clear &Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "&Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepInto.setText(QtGui.QApplication.translate("MainWindow", "Step &Into", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepInto.setToolTip(QtGui.QApplication.translate("MainWindow", "Step Into", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepInto.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBreakpoints.setText(QtGui.QApplication.translate("MainWindow", "&Breakpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBreakpoints.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Statusbar.setText(QtGui.QApplication.translate("MainWindow", "Show St&atusbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Toolbar.setText(QtGui.QApplication.translate("MainWindow", "Show &Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Registers.setText(QtGui.QApplication.translate("MainWindow", "Show &Registers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Memory.setText(QtGui.QApplication.translate("MainWindow", "Show &Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore_Default_Layout.setText(QtGui.QApplication.translate("MainWindow", "Restore Default &Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestore_Default_Layout.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "&Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Undo.setText(QtGui.QApplication.translate("MainWindow", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Undo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Re&do", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Messages.setText(QtGui.QApplication.translate("MainWindow", "Show M&essages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepOver.setText(QtGui.QApplication.translate("MainWindow", "Step &Over", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepOver.setToolTip(QtGui.QApplication.translate("MainWindow", "Step Over", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStepOver.setShortcut(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestart.setText(QtGui.QApplication.translate("MainWindow", "Re&start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestart.setToolTip(QtGui.QApplication.translate("MainWindow", "Restart Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestart.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResume.setText(QtGui.QApplication.translate("MainWindow", "Resu&me", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResume.setToolTip(QtGui.QApplication.translate("MainWindow", "Resume Execution", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResume.setShortcut(QtGui.QApplication.translate("MainWindow", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Memory_Dump.setText(QtGui.QApplication.translate("MainWindow", "Show Memory &Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_LCD_Display.setText(QtGui.QApplication.translate("MainWindow", "Show &LCD Display", None, QtGui.QApplication.UnicodeUTF8))

from ..widget.memorylcdview import MemoryLCDView
from ..widget.myqtreeview import MyQTreeView
