# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtarmsim/ui/preferences.ui'
#
# Created: Thu Nov  2 18:25:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(660, 388)
        self.verticalLayout = QtGui.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabARMSim = QtGui.QWidget()
        self.tabARMSim.setObjectName("tabARMSim")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabARMSim)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.tabARMSim)
        self.groupBox.setTitle("ARMSim")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.labelARMSimCommand = QtGui.QLabel(self.groupBox)
        self.labelARMSimCommand.setObjectName("labelARMSimCommand")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelARMSimCommand)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditARMSimDirectory = QtGui.QLineEdit(self.groupBox)
        self.lineEditARMSimDirectory.setText("")
        self.lineEditARMSimDirectory.setObjectName("lineEditARMSimDirectory")
        self.horizontalLayout.addWidget(self.lineEditARMSimDirectory)
        self.toolButtonARMSimDirectory = QtGui.QToolButton(self.groupBox)
        self.toolButtonARMSimDirectory.setObjectName("toolButtonARMSimDirectory")
        self.horizontalLayout.addWidget(self.toolButtonARMSimDirectory)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditARMSimCommand = QtGui.QLineEdit(self.groupBox)
        self.lineEditARMSimCommand.setObjectName("lineEditARMSimCommand")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditARMSimCommand)
        self.labelARMSimServer = QtGui.QLabel(self.groupBox)
        self.labelARMSimServer.setObjectName("labelARMSimServer")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelARMSimServer)
        self.lineEditARMSimServer = QtGui.QLineEdit(self.groupBox)
        self.lineEditARMSimServer.setText("")
        self.lineEditARMSimServer.setObjectName("lineEditARMSimServer")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditARMSimServer)
        self.labelARMSimPort = QtGui.QLabel(self.groupBox)
        self.labelARMSimPort.setObjectName("labelARMSimPort")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelARMSimPort)
        self.spinBoxARMSimPort = QtGui.QSpinBox(self.groupBox)
        self.spinBoxARMSimPort.setMinimum(8000)
        self.spinBoxARMSimPort.setMaximum(9999)
        self.spinBoxARMSimPort.setProperty("value", 8010)
        self.spinBoxARMSimPort.setObjectName("spinBoxARMSimPort")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxARMSimPort)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabARMSim)
        self.groupBox_2.setTitle("Gcc ARM")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEditARMGccOptions = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditARMGccOptions.setText("")
        self.lineEditARMGccOptions.setObjectName("lineEditARMGccOptions")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditARMGccOptions)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditARMGccCommand = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditARMGccCommand.setText("")
        self.lineEditARMGccCommand.setObjectName("lineEditARMGccCommand")
        self.horizontalLayout_2.addWidget(self.lineEditARMGccCommand)
        self.toolButtonARMGccCommand = QtGui.QToolButton(self.groupBox_2)
        self.toolButtonARMGccCommand.setObjectName("toolButtonARMGccCommand")
        self.horizontalLayout_2.addWidget(self.toolButtonARMGccCommand)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.labelARMGccOptions = QtGui.QLabel(self.groupBox_2)
        self.labelARMGccOptions.setObjectName("labelARMGccOptions")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelARMGccOptions)
        self.labelARMGccCommand = QtGui.QLabel(self.groupBox_2)
        self.labelARMGccCommand.setObjectName("labelARMGccCommand")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelARMGccCommand)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButtonARMSimRestoreDefaults = QtGui.QPushButton(self.tabARMSim)
        self.pushButtonARMSimRestoreDefaults.setObjectName("pushButtonARMSimRestoreDefaults")
        self.horizontalLayout_3.addWidget(self.pushButtonARMSimRestoreDefaults)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabARMSim, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), PreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.lineEditARMSimServer, self.spinBoxARMSimPort)
        PreferencesDialog.setTabOrder(self.spinBoxARMSimPort, self.lineEditARMSimCommand)
        PreferencesDialog.setTabOrder(self.lineEditARMSimCommand, self.lineEditARMSimDirectory)
        PreferencesDialog.setTabOrder(self.lineEditARMSimDirectory, self.toolButtonARMSimDirectory)
        PreferencesDialog.setTabOrder(self.toolButtonARMSimDirectory, self.lineEditARMGccCommand)
        PreferencesDialog.setTabOrder(self.lineEditARMGccCommand, self.toolButtonARMGccCommand)
        PreferencesDialog.setTabOrder(self.toolButtonARMGccCommand, self.lineEditARMGccOptions)
        PreferencesDialog.setTabOrder(self.lineEditARMGccOptions, self.pushButtonARMSimRestoreDefaults)
        PreferencesDialog.setTabOrder(self.pushButtonARMSimRestoreDefaults, self.buttonBox)
        PreferencesDialog.setTabOrder(self.buttonBox, self.tabWidget)

    def retranslateUi(self, PreferencesDialog):
        PreferencesDialog.setWindowTitle(QtGui.QApplication.translate("PreferencesDialog", "QtARMSim Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.labelARMSimCommand.setText(QtGui.QApplication.translate("PreferencesDialog", "ARMSim directory", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonARMSimDirectory.setText(QtGui.QApplication.translate("PreferencesDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferencesDialog", "Command line", None, QtGui.QApplication.UnicodeUTF8))
        self.labelARMSimServer.setText(QtGui.QApplication.translate("PreferencesDialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.labelARMSimPort.setText(QtGui.QApplication.translate("PreferencesDialog", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonARMGccCommand.setText(QtGui.QApplication.translate("PreferencesDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelARMGccOptions.setText(QtGui.QApplication.translate("PreferencesDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.labelARMGccCommand.setText(QtGui.QApplication.translate("PreferencesDialog", "Command line", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonARMSimRestoreDefaults.setText(QtGui.QApplication.translate("PreferencesDialog", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabARMSim), QtGui.QApplication.translate("PreferencesDialog", "ARMSim", None, QtGui.QApplication.UnicodeUTF8))

