#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['paperstream']

package_data = \
{'': ['*'],
 'paperstream': ['build/*',
                 'build\\paperstream/*',
                 'dist/*',
                 'dist\\paperstream/*',
                 'dist\\paperstream\\Include/*',
                 'dist\\paperstream\\input/*',
                 'dist\\paperstream\\input\\1_diaries_to_create/*',
                 'dist\\paperstream\\input\\1_diaries_to_create\\resources/*',
                 'dist\\paperstream\\input\\2_template_to_encode/*',
                 'dist\\paperstream\\input\\3_diaries_to_encode/*',
                 'dist\\paperstream\\lib2to3/*',
                 'dist\\paperstream\\output/*',
                 'dist\\paperstream\\output\\created_diaries/*',
                 'dist\\paperstream\\output\\created_diaries\\a5_references/*',
                 'dist\\paperstream\\output\\encoded_diaries/*',
                 'dist\\paperstream\\output\\temporal/*',
                 'dist\\paperstream\\output\\temporal\\answers_areas/*',
                 'dist\\paperstream\\output\\temporal\\answers_areas\\scannedDiary1/*',
                 'dist\\paperstream\\output\\temporal\\answers_areas\\scannedDiary2/*',
                 'dist\\paperstream\\output\\temporal\\answers_areas\\template_gray_scale/*',
                 'dist\\paperstream\\output\\temporal\\diary_pages/*',
                 'dist\\paperstream\\output\\temporal\\diary_pages\\scannedDiary1/*',
                 'dist\\paperstream\\output\\temporal\\diary_pages\\scannedDiary2/*',
                 'dist\\paperstream\\output\\temporal\\diary_pages\\template_gray_scale/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_0/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_1/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_2/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_3/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_4/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary1\\answer_area_page_5/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_0/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_1/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_2/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_3/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_4/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\scannedDiary2\\answer_area_page_5/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\template_gray_scale/*',
                 'dist\\paperstream\\output\\temporal\\mark_areas\\template_gray_scale\\answer_area_page_0/*',
                 'dist\\paperstream\\static/*',
                 'dist\\paperstream\\static\\downloads/*',
                 'dist\\paperstream\\static\\fonts/*',
                 'input/*',
                 'input\\1_diaries_to_create/*',
                 'input\\1_diaries_to_create\\resources/*',
                 'input\\2_template_to_encode/*',
                 'input\\3_diaries_to_encode/*',
                 'output/*',
                 'output\\created_diaries/*',
                 'output\\created_diaries\\a5_references/*',
                 'output\\encoded_diaries/*',
                 'output\\temporal/*',
                 'static/*',
                 'static\\downloads/*',
                 'static\\fonts/*']}

install_requires = \
['opencv_python>=3.3.0.10',
 'waitress>=1.0.2',
 'falcon>=1.3.0',
 'numpy>=1.12.1',
 'falcon_multipart>=0.2.0',
 'Pillow>=4.3.0',
 'PyPDF2>=1.26.0',
 'reportlab>=3.4.0']

entry_points = \
{'console_scripts': ['paperstream = paperstream.__main__:main']}

setup(name='paperstream',
      version='1.0',
      description='PaperStream web app. Create and encode paper diaries or surveys automatically',
      author='Julio Vega',
      author_email='julio.vega@protonmail.com',
      url='https://paperstream.netlify.com',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3',
     )
