.test: &test
    stage: test
    script: 
        - export TOXENV=''
    tags:
        - docker

test:2.7:
    <<: *test
    image: python:2.7
    script:
        - pip install tox
        - TOXENV=py27 tox

test:pypy:
    <<: *test
    image: pypy:2
    script:
        - pip install tox
        - TOXENV=pypy tox

test:pypy3:
    <<: *test
    image: pypy:3
    script:
        - pip install tox
        - TOXENV=pypy3 tox

test:3.4:
    <<: *test
    image: python:3.4
    script:
        - pip install tox
        - TOXENV=py34 tox

test:3.5:
    <<: *test
    image: python:3.5
    script:
        - pip install tox
        - TOXENV=py35 tox

test:3.6:
    <<: *test
    image: python:3.6
    script:
        - pip install tox
        - TOXENV=py36 tox

test:pep8:
    <<: *test
    image: python:3.6
    script:
        - pip install tox
        - TOXENV=lint tox

test_cov:
    <<: *test
    image: ubuntu:14.04
    script:
        - apt-get update -y
        - apt-get install -y software-properties-common
        - add-apt-repository -y ppa:fkrull/deadsnakes
        - apt-get update -y
        - apt-get upgrade -y
        - apt-get install -y python3.5 python2.7 python-pip
        - pip install tox
        - TOXENV=py27,py35,coverage tox

pages:
    image: python:3.6
    script:
        - apt-get install make
        - pip install tox
        - TOXENV=docs tox
        - mv .tox/docs/html public
    artifacts:
        paths:
            - public
    tags:
        - docker
