# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: pypy
          env: TOXENV=pypy
        - python: 3.6
          env: TOXENV=py27,py36,coverage
        - python: 3.6
          env: TOXENV=lint
        - python: nightly
          env: TOXENV=py37
    allow_failures:
        - env: TOXENV=py37

install:
  - travis_retry pip install tox tox-travis

script:
  - travis_retry tox
