# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/vision/LaserScanCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.vision import LaserScan_pb2 as rst_dot_vision_dot_LaserScan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/vision/LaserScanCollection.proto',
  package='rst.vision',
  syntax='proto2',
  serialized_pb=_b('\n$rst/vision/LaserScanCollection.proto\x12\nrst.vision\x1a\x1arst/vision/LaserScan.proto\"=\n\x13LaserScanCollection\x12&\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x15.rst.vision.LaserScanB\x19\x42\x17LaserScanCollectionType')
  ,
  dependencies=[rst_dot_vision_dot_LaserScan__pb2.DESCRIPTOR,])




_LASERSCANCOLLECTION = _descriptor.Descriptor(
  name='LaserScanCollection',
  full_name='rst.vision.LaserScanCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.vision.LaserScanCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=141,
)

_LASERSCANCOLLECTION.fields_by_name['element'].message_type = rst_dot_vision_dot_LaserScan__pb2._LASERSCAN
DESCRIPTOR.message_types_by_name['LaserScanCollection'] = _LASERSCANCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaserScanCollection = _reflection.GeneratedProtocolMessageType('LaserScanCollection', (_message.Message,), dict(
  DESCRIPTOR = _LASERSCANCOLLECTION,
  __module__ = 'rst.vision.LaserScanCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.vision.LaserScanCollection)
  ))
_sym_db.RegisterMessage(LaserScanCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\027LaserScanCollectionType'))
# @@protoc_insertion_point(module_scope)
