# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/audition/FloatSoundArray.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/audition/FloatSoundArray.proto',
  package='rst.audition',
  syntax='proto2',
  serialized_pb=_b('\n\"rst/audition/FloatSoundArray.proto\x12\x0crst.audition\"&\n\x0f\x46loatSoundArray\x12\x13\n\x0b\x66loatbuffer\x18\x01 \x03(\x02\x42\x15\x42\x13\x46loatSoundArrayType')
)




_FLOATSOUNDARRAY = _descriptor.Descriptor(
  name='FloatSoundArray',
  full_name='rst.audition.FloatSoundArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='floatbuffer', full_name='rst.audition.FloatSoundArray.floatbuffer', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['FloatSoundArray'] = _FLOATSOUNDARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatSoundArray = _reflection.GeneratedProtocolMessageType('FloatSoundArray', (_message.Message,), dict(
  DESCRIPTOR = _FLOATSOUNDARRAY,
  __module__ = 'rst.audition.FloatSoundArray_pb2'
  # @@protoc_insertion_point(class_scope:rst.audition.FloatSoundArray)
  ))
_sym_db.RegisterMessage(FloatSoundArray)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\023FloatSoundArrayType'))
# @@protoc_insertion_point(module_scope)
