package:
  name: ommprotocol
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

about:
  home: https://github.com/insilichem/ommprotocol
  license: LGPL
  summary: Easy to deploy MD protocols for OpenMM

source:
  git_url: https://github.com/insilichem/ommprotocol.git
  git_tag: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - openmm
    - ruamel_yaml
    - parmed
    - openmoltools
    - mdtraj

test:
  imports:
    - ommprotocol
