FILETYPES = {
'doc': 'Microsoft Word Document',
'docx': 'Microsoft Word Open XML Document',
'log': 'Log File',
'msg': 'Outlook Mail Message',
'pages': 'Pages Document',
'rtf': 'Rich Text Format File',
'txt': 'Plain Text File',
'wpd': 'WordPerfect Document',
'wps': 'Microsoft Works Word Processor Document',
'blg': 'Windows Binary Performance Log File',
'csv': 'Comma Separated Values File',
'dat': 'Data File',
'efx': 'eFax Document',
'pps': 'PowerPoint Slide Show',
'ppt': 'PowerPoint Presentation',
'pptx': 'PowerPoint Open XML Presentation',
'sdf': 'Standard Data File',
'vcf': 'vCard File',
'xml': 'XML File',
'aac': 'Advanced Audio Coding File',
'aif': 'Audio Interchange File Format',
'iff': 'Interchange File Format',
'mp3': 'MP3 Audio File',
'mpa': 'MPEG-2 Audio File',
'ra': 'Real Audio File',
'wav': 'WAVE Audio File',
'wma': 'Windows Media Audio File',
'3g2': '3GPP2 Multimedia File',
'3gp': '3GPP Multimedia File',
'asf': 'Advanced Systems Format File',
'asx': 'Microsoft ASF Redirector File',
'avi': 'Audio Video Interleave File',
'flv': 'Flash Video File',
'mov': 'Apple QuickTime Movie',
'mp4': 'MPEG-4 Video File',
'mpg': 'MPEG Video File',
'rm': 'Real Media File',
'swf': 'Flash Movie',
'vob': 'DVD Video Object File',
'wmv': 'Windows Media Video File',
'3dm': 'Rhino 3D Model',
'max': '3ds Max Scene File',
'bmp': 'Bitmap Image File',
'gif': 'Graphical Interchange Format File',
'jpg': 'JPEG Image File',
'png': 'Portable Network Graphic',
'psd': 'Adobe Photoshop Document',
'pspimage': 'PaintShop Photo Pro Image',
'thm': 'Thumbnail Image File',
'tif': 'Tagged Image File',
'yuv': 'YUV Encoded Image File',
'ai': 'Adobe Illustrator File',
'drw': 'Drawing File',
'eps': 'Encapsulated PostScript File',
'ps': 'PostScript File',
'svg': 'Scalable Vector Graphics File',
'indd': 'Adobe InDesign File',
'pct': 'Picture File',
'pdf': 'PDF',
'qxd': 'QuarkXPress Document',
'qxp': 'QuarkXPress Project File',
'rels': 'Open Office XML Relationships File',
'wks': 'Works Spreadsheet',
'xls': 'Excel Spreadsheet',
'xlsx': 'Microsoft Excel Open XML Spreadsheet',
'accdb': 'Access 2007 Database File',
'db': 'Database File',
'mdb': 'Microsoft Access Database',
'pdb': 'Program Database',
'sql': 'Structured Query Language Data',
'app': 'Mac OS X Application',
'bat': 'DOS Batch File',
'cgi': 'Common Gateway Interface Script',
'com': 'DOS Command File',
'exe': 'Windows Executable File',
'jar': 'Java Archive File',
'pif': 'Program Information File',
'vb': 'VBScript File',
'wsf': 'Windows Script File',
'gam': 'Saved Game File',
'nes': 'Nintendo (NES) ROM File',
'rom': 'N64 Game ROM File',
'sav': 'Saved Game',
'dwg': 'AutoCAD Drawing Database File',
'dxf': 'Drawing Exchange Format File',
'pln': 'ArchiCAD Project File',
'gpx': 'GPS Exchange File',
'kml': 'Keyhole Markup Language File',
'asp': 'Active Server Page',
'cer': 'Internet Security Certificate',
'csr': 'Certificate Signing Request File',
'css': 'Cascading Style Sheet',
'htm': 'Hypertext Markup Language File',
'html': 'Hypertext Markup Language File',
'js': 'JavaScript File',
'jsp': 'Java Server Page',
'php': 'Hypertext Preprocessor File',
'rss': 'Rich Site Summary',
'xhtml': 'Extensible Hypertext Markup Language File',
'8bi': 'Photoshop Plug-in',
'plugin': 'Mac OS X Plug-in',
'xll': 'Excel Add-In File',
'fnt': 'Windows Font File',
'fon': 'Generic Font File',
'otf': 'OpenType Font',
'ttf': 'TrueType Font',
'cab': 'Windows Cabinet File',
'cpl': 'Windows Control Panel',
'cur': 'Windows Cursor',
'dll': 'Dynamic Link Library',
'dmp': 'Windows Memory Dump',
'drv': 'Device Driver',
'lnk': 'File Shortcut',
'sys': 'Windows System File',
'cfg': 'Configuration File',
'ini': 'Windows Initialization File',
'keychain': 'Mac OS X Keychain File',
'prf': 'Outlook Profile File',
'bin': 'Macbinary Encoded File',
'hqx': 'BinHex 4.0 Encoded File',
'mim': 'Multi-Purpose Internet Mail Message File',
'uue': 'Uuencoded File',
'7z': '7-Zip Compressed File',
'deb': 'Debian Software Package',
'gz': 'Gnu Zipped Archive',
'pkg': 'Mac OS X Installer Package',
'rar': 'WinRAR Compressed Archive',
'sit': 'Stuffit Archive',
'sitx': 'Stuffit X Archive',
'tar.gz': 'Tarball File',
'zip': 'Zipped File',
'zipx': 'Extended Zip File',
'dmg': 'Mac OS X Disk Image',
'iso': 'Disc Image File',
'toast': 'Toast Disc Image',
'vcd': 'Virtual CD',
'c': 'C/C++ Source Code File',
'class': 'Java Class File',
'cpp': 'C++ Source Code File',
'cs': 'Visual C# Source Code File',
'dtd': 'Document Type Definition File',
'java': 'Java Source Code File',
'm': 'Objective-C Implementation File',
'pl': 'Perl Script',
'bak': 'Backup File',
'gho': 'Norton Ghost Backup File',
'ori': 'Original File',
'tmp': 'Temporary File',
'dbx': 'Outlook Express E-mail Folder',
'key': 'Keynote Presentation',
'msi': 'Windows Installer Package',
'part': 'Partially Downloaded File',
'torrent': 'BitTorrent File',
}
