
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-27T14:52:14+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb7016638974131cd3c1f308d4046ec02b6bc2ad",
 "version": "0.0.1.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
