
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-14T15:12:35-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "30f2ebf8dea294bd1edff15ddcb2c518e1b8f347",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
