
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-06T09:33:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "01f5f7ebcf78ab33d3f88715b5752c8cd731ef6a",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
