
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-15T12:15:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "21ad379888de37e49291a991ce19fdb2cbce0d14",
 "version": "0.3.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
