# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName("mainWin")
        mainWin.resize(1226, 625)
        self.widgMain = QtWidgets.QWidget(mainWin)
        self.widgMain.setObjectName("widgMain")
        self.gridLayout = QtWidgets.QGridLayout(self.widgMain)
        self.gridLayout.setObjectName("gridLayout")
        self.txtHeader = QtWidgets.QLabel(self.widgMain)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtHeader.setFont(font)
        self.txtHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHeader.setObjectName("txtHeader")
        self.gridLayout.addWidget(self.txtHeader, 0, 0, 1, 1)
        self.headProbSpec = QtWidgets.QLabel(self.widgMain)
        self.headProbSpec.setObjectName("headProbSpec")
        self.gridLayout.addWidget(self.headProbSpec, 2, 1, 1, 1)
        self.saveProbSpec = QtWidgets.QPushButton(self.widgMain)
        self.saveProbSpec.setEnabled(False)
        self.saveProbSpec.setObjectName("saveProbSpec")
        self.gridLayout.addWidget(self.saveProbSpec, 2, 2, 1, 1)
        self.btnSpecActions = QtWidgets.QPushButton(self.widgMain)
        self.btnSpecActions.setEnabled(False)
        self.btnSpecActions.setObjectName("btnSpecActions")
        self.gridLayout.addWidget(self.btnSpecActions, 2, 3, 1, 1)
        self.pic = QtWidgets.QLabel(self.widgMain)
        self.pic.setObjectName("pic")
        self.gridLayout.addWidget(self.pic, 3, 0, 3, 1)
        self.headProbReal = QtWidgets.QLabel(self.widgMain)
        self.headProbReal.setObjectName("headProbReal")
        self.gridLayout.addWidget(self.headProbReal, 4, 1, 1, 1)
        self.saveProbReal = QtWidgets.QPushButton(self.widgMain)
        self.saveProbReal.setEnabled(False)
        self.saveProbReal.setObjectName("saveProbReal")
        self.gridLayout.addWidget(self.saveProbReal, 4, 2, 1, 1)
        self.btnRealActions = QtWidgets.QPushButton(self.widgMain)
        self.btnRealActions.setEnabled(False)
        self.btnRealActions.setObjectName("btnRealActions")
        self.gridLayout.addWidget(self.btnRealActions, 4, 3, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.widgMain)
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout.addWidget(self.btnOpen, 6, 0, 1, 4)
        self.btnNewProb = QtWidgets.QPushButton(self.widgMain)
        self.btnNewProb.setObjectName("btnNewProb")
        self.gridLayout.addWidget(self.btnNewProb, 7, 0, 1, 4)
        self.btnClear = QtWidgets.QPushButton(self.widgMain)
        self.btnClear.setObjectName("btnClear")
        self.gridLayout.addWidget(self.btnClear, 8, 0, 1, 4)
        self.txtProbSpec = QtWidgets.QLabel(self.widgMain)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.txtProbSpec.setPalette(palette)
        self.txtProbSpec.setObjectName("txtProbSpec")
        self.gridLayout.addWidget(self.txtProbSpec, 3, 1, 1, 3)
        self.txtProbReal = QtWidgets.QLabel(self.widgMain)
        self.txtProbReal.setObjectName("txtProbReal")
        self.gridLayout.addWidget(self.txtProbReal, 5, 1, 1, 3)
        self.txtWorkspace = QtWidgets.QLabel(self.widgMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtWorkspace.setFont(font)
        self.txtWorkspace.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWorkspace.setObjectName("txtWorkspace")
        self.gridLayout.addWidget(self.txtWorkspace, 0, 2, 1, 1)
        mainWin.setCentralWidget(self.widgMain)
        self.menubar = QtWidgets.QMenuBar(mainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWin)
        self.statusbar.setObjectName("statusbar")
        mainWin.setStatusBar(self.statusbar)
        self.fileMenu = QtWidgets.QAction(mainWin)
        self.fileMenu.setObjectName("fileMenu")
        self.actionOpen = QtWidgets.QAction(mainWin)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(mainWin)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen_documentation = QtWidgets.QAction(mainWin)
        self.actionOpen_documentation.setObjectName("actionOpen_documentation")
        self.actionAbout_SDElib_1_0 = QtWidgets.QAction(mainWin)
        self.actionAbout_SDElib_1_0.setObjectName("actionAbout_SDElib_1_0")
        self.actionExit = QtWidgets.QAction(mainWin)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWin)
        QtCore.QMetaObject.connectSlotsByName(mainWin)
        mainWin.setTabOrder(self.saveProbSpec, self.saveProbReal)
        mainWin.setTabOrder(self.saveProbReal, self.btnOpen)
        mainWin.setTabOrder(self.btnOpen, self.btnNewProb)

    def retranslateUi(self, mainWin):
        _translate = QtCore.QCoreApplication.translate
        mainWin.setWindowTitle(_translate("mainWin", "sdelib"))
        self.txtHeader.setToolTip(_translate("mainWin", "<html><head/><body><p>In program specification mode, you either create a program specification from scratch with Create New Problem Specification, or you create a problem from a template with Full Example Problem Specifications.</p></body></html>"))
        self.txtHeader.setText(_translate("mainWin", "Main window"))
        self.headProbSpec.setText(_translate("mainWin", "Problem specification object state:"))
        self.saveProbSpec.setText(_translate("mainWin", "Save"))
        self.btnSpecActions.setText(_translate("mainWin", "Specification actions"))
        self.pic.setText(_translate("mainWin", "<html><head/><body><p><img src=\":/newPrefix/Operation.jpg\"/></p></body></html>"))
        self.headProbReal.setText(_translate("mainWin", "Problem realization object state:"))
        self.saveProbReal.setText(_translate("mainWin", "Save"))
        self.btnRealActions.setText(_translate("mainWin", "Realization actions"))
        self.btnOpen.setText(_translate("mainWin", "Open SDE object from .sde file"))
        self.btnNewProb.setText(_translate("mainWin", "Create New Problem Specification"))
        self.btnClear.setText(_translate("mainWin", "Clear objects from memory (remember to save objects first)"))
        self.txtProbSpec.setText(_translate("mainWin", "None-object"))
        self.txtProbReal.setText(_translate("mainWin", "None-object"))
        self.txtWorkspace.setText(_translate("mainWin", "Workspace of objects"))
        self.menuFile.setTitle(_translate("mainWin", "File"))
        self.fileMenu.setText(_translate("mainWin", "New SDE problem specification"))
        self.actionOpen.setText(_translate("mainWin", "Open"))
        self.actionSave.setText(_translate("mainWin", "Save"))
        self.actionOpen_documentation.setText(_translate("mainWin", "Open documentation"))
        self.actionAbout_SDElib_1_0.setText(_translate("mainWin", "About SDElib 1.0"))
        self.actionExit.setText(_translate("mainWin", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWin = QtWidgets.QMainWindow()
    ui = Ui_mainWin()
    ui.setupUi(mainWin)
    mainWin.show()
    sys.exit(app.exec_())

