# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/tracking/TrackingInfoCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.tracking import TrackingInfo_pb2 as rst_dot_tracking_dot_TrackingInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/tracking/TrackingInfoCollection.proto',
  package='rst.tracking',
  syntax='proto2',
  serialized_pb=_b('\n)rst/tracking/TrackingInfoCollection.proto\x12\x0crst.tracking\x1a\x1frst/tracking/TrackingInfo.proto\"E\n\x16TrackingInfoCollection\x12+\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1a.rst.tracking.TrackingInfoB\x1c\x42\x1aTrackingInfoCollectionType')
  ,
  dependencies=[rst_dot_tracking_dot_TrackingInfo__pb2.DESCRIPTOR,])




_TRACKINGINFOCOLLECTION = _descriptor.Descriptor(
  name='TrackingInfoCollection',
  full_name='rst.tracking.TrackingInfoCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.tracking.TrackingInfoCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=161,
)

_TRACKINGINFOCOLLECTION.fields_by_name['element'].message_type = rst_dot_tracking_dot_TrackingInfo__pb2._TRACKINGINFO
DESCRIPTOR.message_types_by_name['TrackingInfoCollection'] = _TRACKINGINFOCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackingInfoCollection = _reflection.GeneratedProtocolMessageType('TrackingInfoCollection', (_message.Message,), dict(
  DESCRIPTOR = _TRACKINGINFOCOLLECTION,
  __module__ = 'rst.tracking.TrackingInfoCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.tracking.TrackingInfoCollection)
  ))
_sym_db.RegisterMessage(TrackingInfoCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\032TrackingInfoCollectionType'))
# @@protoc_insertion_point(module_scope)
