# coding: utf-8

"""
    BlueLens Index API

    This is a bl-api-index server.

    OpenAPI spec version: 0.0.1
    Contact: devops@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import stylelens_index
from stylelens_index.rest import ApiException
from stylelens_index.models.add_image_response import AddImageResponse


class TestAddImageResponse(unittest.TestCase):
    """ AddImageResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddImageResponse(self):
        """
        Test AddImageResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = stylelens_index.models.add_image_response.AddImageResponse()
        pass


if __name__ == '__main__':
    unittest.main()
