# -*- coding: utf-8 -*-
"""
Exit codes for the application.

:author: Joe Joyce <joe@decafjoe.com>
:copyright: Copyright (c) Joe Joyce and contributors, 2016-2017.
:license: BSD
"""
CANCELED = 14
DECRYPTION_FAILED = 16
ENCRYPTION_FAILED = 13
FILE_EXISTS = 12
MISSING_FILE = 11
MISSING_GPG = 10
PASTEBOARD_COPY_FAILED = 26
SRM_FAILED = 17
UNRECOGNIZED_ACCOUNT = 19
UNRECOGNIZED_ALIAS = 20
UNRECOGNIZED_CODE = 23
UNRECOGNIZED_FILE = 15
UNRECOGNIZED_POLICY = 21
UNRECOGNIZED_QUESTION = 22
UNSET_PASSWORD = 25
UNSUPPORTED_PASTEBOARD = 24
VALIDATION_ERROR = 18
