JENKINS_JOB_CTX = {
    'STACK_COMPUTE_COUNT': '2',
    'AWS_SSH_KEY': 'jenkins-mk',
    'HEAT_STACK_PUBLIC_NET': 'public',
    'OPENSTACK_API_PROJECT_ID': '',
    'ASK_ON_ERROR': False,
    'STACK_INSTALL': 'core,k8s,calico',
    'STACK_TEMPLATE_CREDENTIALS': 'gerrit',
    'STACK_TEMPLATE_URL': 'ssh://mcp-jenkins@gerrit.mcp.mirantis.net:29418/mk/heat-templates',
    'HEAT_STACK_ZONE': 'mcp-mk',
    'SALT_OVERRIDES': '',
    'TEST_K8S_CONFORMANCE_IMAGE': 'docker-dev-virtual.docker.mirantis.net/mirantis/kubernetes/k8s-conformance:v1.7.3-1_1503652362277',
    'STACK_RECLASS_BRANCH': '',
    'STACK_NAME': '',
    'STACK_REUSE': False,
    'OPENSTACK_API_CREDENTIALS': 'openstack-devcloud-credentials',
    'TEST_TEMPEST_TARGET': '',
    'STACK_DELETE': False,
    'TEST_K8S_API_SERVER': 'http://127.0.0.1:8080',
    'OPENSTACK_API_VERSION': '3',
    'OPENSTACK_API_PROJECT': 'mcp-mk',
    'OPENSTACK_API_CLIENT': '',
    'STACK_TEMPLATE_BRANCH': 'master',
    'STACK_CLEANUP_JOB': 'deploy-stack-cleanup',
    'AWS_API_CREDENTIALS': 'aws-credentials',
    'TEST_DOCKER_INSTALL': True,
    'SALT_MASTER_CREDENTIALS': 'salt-qa-credentials',
    'OPENSTACK_API_URL': 'https://cloud-cz.bud.mirantis.net:5000',
    'AWS_STACK_REGION': 'us-west-2',
    'HEAT_STACK_ENVIRONMENT': 'devcloud',
    'STACK_TYPE': 'aws',
    'OPENSTACK_API_USER_DOMAIN': 'default',
    'STACK_TEST': '',
    'STACK_TEMPLATE': 'k8s_ha_calico_sm',
    'SALT_MASTER_URL': '',
    'TEST_TEMPEST_PATTERN': '',
    'OPENSTACK_API_PROJECT_DOMAIN': 'default',
    'TEST_TEMPEST_IMAGE': 'sandbox-docker-prod-local.docker.mirantis.net/mirantis/rally_tempest:0.1'
}
JENKINS_USERNAME = 'model-manager'
JENKINS_PASSWORD = 't&2FLaB]2!'
