#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nbconvert_reportlab']

package_data = \
{'': ['*']}

install_requires = \
['nbconvert', 'reportlab', 'pdfrw>=0.3', 'matplotlib', 'mistune>=0.8.1']

entry_points = \
{'nbconvert.exporters': ['pdf-rl = nbconvert_reportlab:ReportlabExporter']}

setup(name='nbconvert_reportlab',
      version='0.2',
      description='Convert notebooks to PDF using Reportlab',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/takluyver/nbconvert-reportlab',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
