# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/vision/EncodedImageCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.vision import EncodedImage_pb2 as rst_dot_vision_dot_EncodedImage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/vision/EncodedImageCollection.proto',
  package='rst.vision',
  syntax='proto2',
  serialized_pb=_b('\n\'rst/vision/EncodedImageCollection.proto\x12\nrst.vision\x1a\x1drst/vision/EncodedImage.proto\"C\n\x16\x45ncodedImageCollection\x12)\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x18.rst.vision.EncodedImageB\x1c\x42\x1a\x45ncodedImageCollectionType')
  ,
  dependencies=[rst_dot_vision_dot_EncodedImage__pb2.DESCRIPTOR,])




_ENCODEDIMAGECOLLECTION = _descriptor.Descriptor(
  name='EncodedImageCollection',
  full_name='rst.vision.EncodedImageCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.vision.EncodedImageCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=153,
)

_ENCODEDIMAGECOLLECTION.fields_by_name['element'].message_type = rst_dot_vision_dot_EncodedImage__pb2._ENCODEDIMAGE
DESCRIPTOR.message_types_by_name['EncodedImageCollection'] = _ENCODEDIMAGECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncodedImageCollection = _reflection.GeneratedProtocolMessageType('EncodedImageCollection', (_message.Message,), dict(
  DESCRIPTOR = _ENCODEDIMAGECOLLECTION,
  __module__ = 'rst.vision.EncodedImageCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.vision.EncodedImageCollection)
  ))
_sym_db.RegisterMessage(EncodedImageCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\032EncodedImageCollectionType'))
# @@protoc_insertion_point(module_scope)
