
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-16T11:43:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0a8f43ad0fe0abb39c24bd131cb09455759576c",
 "version": "0.2.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
