# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/communicationpatterns/TaskStateCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.communicationpatterns import TaskState_pb2 as rst_dot_communicationpatterns_dot_TaskState__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/communicationpatterns/TaskStateCollection.proto',
  package='rst.communicationpatterns',
  syntax='proto2',
  serialized_pb=_b('\n3rst/communicationpatterns/TaskStateCollection.proto\x12\x19rst.communicationpatterns\x1a)rst/communicationpatterns/TaskState.proto\"L\n\x13TaskStateCollection\x12\x35\n\x07\x65lement\x18\x01 \x03(\x0b\x32$.rst.communicationpatterns.TaskStateB\x19\x42\x17TaskStateCollectionType')
  ,
  dependencies=[rst_dot_communicationpatterns_dot_TaskState__pb2.DESCRIPTOR,])




_TASKSTATECOLLECTION = _descriptor.Descriptor(
  name='TaskStateCollection',
  full_name='rst.communicationpatterns.TaskStateCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.communicationpatterns.TaskStateCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=201,
)

_TASKSTATECOLLECTION.fields_by_name['element'].message_type = rst_dot_communicationpatterns_dot_TaskState__pb2._TASKSTATE
DESCRIPTOR.message_types_by_name['TaskStateCollection'] = _TASKSTATECOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskStateCollection = _reflection.GeneratedProtocolMessageType('TaskStateCollection', (_message.Message,), dict(
  DESCRIPTOR = _TASKSTATECOLLECTION,
  __module__ = 'rst.communicationpatterns.TaskStateCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.communicationpatterns.TaskStateCollection)
  ))
_sym_db.RegisterMessage(TaskStateCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\027TaskStateCollectionType'))
# @@protoc_insertion_point(module_scope)
