
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ec99e1fe0c868da3541b581b3795659f2fccff94",
 "version": "1895"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
