- project:
    name: openstack/python-ironicclient
    check:
      jobs:
        - ironicclient-tempest-dsvm-src:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - ironicclient-dsvm-functional:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
    gate:
      jobs:
        - ironicclient-tempest-dsvm-src:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
        - ironicclient-dsvm-functional:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
