# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useragents', '0002_auto_20171103_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip',
            new_name='address',
        ),
        migrations.AddField(
            model_name='ip',
            name='visits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='path',
            name='visits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useragent',
            name='visits',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
