# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useragents', '0003_auto_20171104_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
