# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useragents', '0006_auto_20171104_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='visits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='path',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='visits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='string',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='visits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
