# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/dynamics/JointTorques.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/dynamics/JointTorques.proto',
  package='rst.dynamics',
  syntax='proto2',
  serialized_pb=_b('\n\x1frst/dynamics/JointTorques.proto\x12\x0crst.dynamics\"#\n\x0cJointTorques\x12\x13\n\x07torques\x18\x01 \x03(\x02\x42\x02\x10\x01\x42\x12\x42\x10JointTorquesType')
)




_JOINTTORQUES = _descriptor.Descriptor(
  name='JointTorques',
  full_name='rst.dynamics.JointTorques',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='torques', full_name='rst.dynamics.JointTorques.torques', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['JointTorques'] = _JOINTTORQUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointTorques = _reflection.GeneratedProtocolMessageType('JointTorques', (_message.Message,), dict(
  DESCRIPTOR = _JOINTTORQUES,
  __module__ = 'rst.dynamics.JointTorques_pb2'
  # @@protoc_insertion_point(class_scope:rst.dynamics.JointTorques)
  ))
_sym_db.RegisterMessage(JointTorques)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\020JointTorquesType'))
_JOINTTORQUES.fields_by_name['torques'].has_options = True
_JOINTTORQUES.fields_by_name['torques']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
