
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-31T12:34:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f6155bb4c25fc42a2dbdc6ba365100ff8ed930e",
 "version": "0.3.1.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
