# This file is automatically generated from sisl setup.py
released = True

# Git information (specific commit, etc.)
git_revision = '7370f9c320bb56473d820b31d814c4342ac7b813'
git_revision_short = git_revision[:7]
git_count = '0'

# Version information
major   = 0
minor   = 9
micro   = 1
version = '.'.join(map(str,[major, minor, micro]))
release = version

if not released:
    # Add git-revision to the version string
    version += '+' + git_count

# BibTeX information if people wish to cite
bibtex = '''@misc{{zerothi_sisl,
    author = {{Papior, Nick R.}},
    title  = {{sisl: v{0}}},
    doi    = {{10.5281/zenodo.597181}},
    url    = {{https://doi.org/10.5281/zenodo.597181}},
}}'''.format(version)

def cite():
    return bibtex
