
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-01T12:44:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cb4c812a44546ba8e6b5ed7e9b9766f026e18a5",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
