#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

entry_points = \
{'console_scripts': ['pytaco = pytaco:main']}

setup(name='pytaco',
      version='1.0.1',
      description='How many tacos for a meetup?',
      author='Mariatta Wijaya',
      author_email='mariatta.wijaya@gmail.com',
      url='https://github.com/Mariatta/taco-py',
      py_modules=['pytaco'],
      entry_points=entry_points,
      python_requires='>=3.6',
     )
