
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-21T08:03:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "acc843f88b0e46b907cf6a1648f4a6ecea87e83d",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
