
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d86d0e36921b4dda437688665eb17c93b361f9ea",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
