# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/hri/Head.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.geometry import BoundingBox3DFloat_pb2 as rst_dot_geometry_dot_BoundingBox3DFloat__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/hri/Head.proto',
  package='rst.hri',
  syntax='proto2',
  serialized_pb=_b('\n\x12rst/hri/Head.proto\x12\x07rst.hri\x1a%rst/geometry/BoundingBox3DFloat.proto\"7\n\x04Head\x12/\n\x05shape\x18\x01 \x02(\x0b\x32 .rst.geometry.BoundingBox3DFloatB\nB\x08HeadType')
  ,
  dependencies=[rst_dot_geometry_dot_BoundingBox3DFloat__pb2.DESCRIPTOR,])




_HEAD = _descriptor.Descriptor(
  name='Head',
  full_name='rst.hri.Head',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='rst.hri.Head.shape', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=125,
)

_HEAD.fields_by_name['shape'].message_type = rst_dot_geometry_dot_BoundingBox3DFloat__pb2._BOUNDINGBOX3DFLOAT
DESCRIPTOR.message_types_by_name['Head'] = _HEAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Head = _reflection.GeneratedProtocolMessageType('Head', (_message.Message,), dict(
  DESCRIPTOR = _HEAD,
  __module__ = 'rst.hri.Head_pb2'
  # @@protoc_insertion_point(class_scope:rst.hri.Head)
  ))
_sym_db.RegisterMessage(Head)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\010HeadType'))
# @@protoc_insertion_point(module_scope)
