
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c99ecd6143cdd0eb2a6707c236d78c49f1cd1365",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
