# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='address_select',
            field=models.CharField(choices=[('full', 'Ввод полного адреса'), ('local', 'Ввод локального адреса'), ('contacts', 'Ввод контактов')], default='full', help_text='Выбор вида отображаемой формы адреса', max_length=30, verbose_name='Форма ввода адреса'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='delivery_hook',
            field=models.CharField(blank=True, help_text='Задайте, если для получения цены и определения адреса доставки используется отдельная логика', max_length=30, verbose_name='Метод определения цены'),
        ),
    ]
