# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0002_auto_20160807_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.IntegerField(choices=[(1, 'Да/Нет'), (2, 'Целое число'), (3, 'Дробное число'), (4, 'Строка до 500 символов')], verbose_name='Тип значения')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='django_shop.ProductCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'дополнительное поле',
                'verbose_name_plural': 'дополнительные поля',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=550)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='django_shop.ProductCategoryCustomField')),
            ],
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='address_select',
            field=models.CharField(choices=[('full', 'Ввод полного адреса'), ('local', 'Ввод локального адреса'), ('contacts', 'Ввод контактов'), ('widget', 'Ввод c помощью виджета')], default='full', help_text='Выбор вида отображаемой формы адреса', max_length=30, verbose_name='Форма ввода адреса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Описание, состоящее из одного абзаца текста, помещается рядом с картинкой товара в каталоге.', verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='productcustomfieldvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='django_shop.Product'),
        ),
    ]
