# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0006_auto_20160813_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorycustomfield',
            options={'ordering': ('-priority', 'pk'), 'verbose_name': 'характеристика', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AlterModelOptions(
            name='productcustomfieldvalue',
            options={'ordering': ('-field__priority', '-field__pk'), 'verbose_name': 'характеристика', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Полное описание продукта, будет показано в его карточке.', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='productcategorycustomfield',
            name='choices',
            field=models.CharField(blank=True, help_text='Если у характеристики предполагается ограниченное число значений, напишите их здесь через запятую', max_length=1000, verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='productcustomfieldvalue',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=550),
        ),
        migrations.AlterUniqueTogether(
            name='productcustomfieldvalue',
            unique_together=set([('product', 'field')]),
        ),
    ]
