# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0009_auto_20160818_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_edit_important', 'Can edit important fields'),), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-priority', 'pk'), 'permissions': (('can_edit_important', 'Can edit important fields'),), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Отображать товар как новинку', verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если старая цена указана, товар отображается как акционный', max_digits=9, null=True, verbose_name='Старая цена'),
        ),
    ]
