# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0010_auto_20160820_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('product_can_edit_important', 'Can edit important fields'),), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-priority', 'pk'), 'permissions': (('category_can_edit_important', 'Can edit important fields'),), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
