# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 14:37
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0011_auto_20160820_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Стоимость закупки'),
        ),
    ]
