# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0012_productorder_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='priority',
            field=models.IntegerField(choices=[(-10, -10), (-9, -9), (-8, -8), (-7, -7), (-6, -6), (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, help_text='Чем выше приоритет, тем выше в списке появится объект', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='priority',
            field=models.IntegerField(choices=[(-10, -10), (-9, -9), (-8, -8), (-7, -7), (-6, -6), (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, help_text='Чем выше приоритет, тем выше в списке появится объект', verbose_name='Приоритет'),
        ),
    ]
