# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0013_auto_20161217_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'ordering': ['-priority'], 'verbose_name': 'способ доставки', 'verbose_name_plural': 'способы доставки'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['-priority'], 'verbose_name': 'способ оплаты', 'verbose_name_plural': 'способы оплаты'},
        ),
    ]
