# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0014_auto_20161217_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=django_shop.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=django_shop.models.get_upload_path, verbose_name='Изображение'),
        ),
    ]
