# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0015_auto_20170106_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Спрятанные категории не отображаются вообще нигде', verbose_name='Спрятать'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='type',
            field=models.CharField(choices=[('basic', 'Базовая (в меню)'), ('secondary', 'Вторичная (для группировки)'), ('brand', 'Бренд')], default='basic', max_length=20, verbose_name='Тип'),
        ),
    ]
