# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0016_auto_20170210_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_shop.ProductCategory', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='type',
            field=models.CharField(choices=[('basic', 'Базовая (в меню)'), ('secondary', 'Вторичная (для группировки)'), ('holiday', 'Праздник'), ('brand', 'Бренд')], default='basic', max_length=20, verbose_name='Тип'),
        ),
    ]
