# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0018_auto_20170216_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='always_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='Включите, если товар должен отображаться, даже если его нет в наличии', verbose_name='Виден всегда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_unlimited',
            field=models.BooleanField(db_index=True, default=False, help_text='Если количество товара неограничено - для него не нужно заводить поставки', verbose_name='Количество неорганичено'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Спрятанные категории не отображаются вообще нигде', verbose_name='Спрятать'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='quantity',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=9, verbose_name='Количество'),
        ),
    ]
