# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0019_auto_20170226_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
