# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0021_auto_20170402_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Количество'),
        ),
    ]
