# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0022_auto_20170404_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerscart',
            options={'ordering': ['-updated'], 'verbose_name': 'корзина клиента', 'verbose_name_plural': 'корзины клиентов'},
        ),
    ]
