# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_shop', '0023_auto_20170406_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('external_id', models.CharField(max_length=11, verbose_name='Код')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='is_autogenerated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сегенерирован автоматически'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='options',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Служебная информация'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_shop.DeliveryCity', verbose_name='Город'),
        ),
    ]
