language: python
python: 2.7
sudo: false
env:
  - TOX_ENV=py27
  - TOX_ENV=py27-ansible18
install:
  - pip install setuptools-git
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  irc:
    - "irc.freenode.org#bsdploy"
  on_success: change
  on_failure: change
