#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['kartoffel']

package_data = \
{'': ['*']}

install_requires = \
['stdlib-list']

entry_points = \
{'console_scripts': ['kartoffel = kartoffel:main']}

setup(name='kartoffel',
      version='0.1',
      description='Identify modules used in a Python application by running it.',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://gitlab.com/takluyver/kartoffel',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
