# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/kinematics/LinearVelocitiesCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.kinematics import LinearVelocities_pb2 as rst_dot_kinematics_dot_LinearVelocities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/kinematics/LinearVelocitiesCollection.proto',
  package='rst.kinematics',
  syntax='proto2',
  serialized_pb=_b('\n/rst/kinematics/LinearVelocitiesCollection.proto\x12\x0erst.kinematics\x1a%rst/kinematics/LinearVelocities.proto\"O\n\x1aLinearVelocitiesCollection\x12\x31\n\x07\x65lement\x18\x01 \x03(\x0b\x32 .rst.kinematics.LinearVelocitiesB B\x1eLinearVelocitiesCollectionType')
  ,
  dependencies=[rst_dot_kinematics_dot_LinearVelocities__pb2.DESCRIPTOR,])




_LINEARVELOCITIESCOLLECTION = _descriptor.Descriptor(
  name='LinearVelocitiesCollection',
  full_name='rst.kinematics.LinearVelocitiesCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.kinematics.LinearVelocitiesCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=185,
)

_LINEARVELOCITIESCOLLECTION.fields_by_name['element'].message_type = rst_dot_kinematics_dot_LinearVelocities__pb2._LINEARVELOCITIES
DESCRIPTOR.message_types_by_name['LinearVelocitiesCollection'] = _LINEARVELOCITIESCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LinearVelocitiesCollection = _reflection.GeneratedProtocolMessageType('LinearVelocitiesCollection', (_message.Message,), dict(
  DESCRIPTOR = _LINEARVELOCITIESCOLLECTION,
  __module__ = 'rst.kinematics.LinearVelocitiesCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.kinematics.LinearVelocitiesCollection)
  ))
_sym_db.RegisterMessage(LinearVelocitiesCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\036LinearVelocitiesCollectionType'))
# @@protoc_insertion_point(module_scope)
