language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov coveralls
script:
    - mv pychemkin pychemkin_backup
    - mv setup.py setup.py.backup
    - ls
    
    # test install from pip
    - pip install pychemkin
    - ls
    - py.test
    
    #recover
    - mv pychemkin_backup pychemkin
    - mv setup.py.backup setup.py
    - ls
    - pip uninstall --yes pychemkin
    - python setup.py sdist --format=tar
    - pip install dist/pychemkin-1.0.1.tar
    - py.test
    
after_success:
    - coveralls
