language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov coveralls
script:
    - python setup.py sdist --format=tar
    - ls
    - pip install dist/pychemkin-0.1.0.tar
    - py.test
after_success:
    - coveralls
