class EkkoPropertyNames:
    TS3_SERVER_HOST = 'EKKO_TS3_SERVER_HOST'
    TS3_SERVER_PORT = 'EKKO_TS3_SERVER_PORT'
    TS3_USERNAME = 'EKKO_TS3_USERNAME'
    TS3_IDENTITY = 'EKKO_TS3_IDENTITY'
    TS3_UNIQUE_ID = 'EKKO_TS3_UNIQUEID'
    TS3_CLIENT_APIKEY = 'EKKO_TS3_CLIENT_APIKEY'
    TS3_CHANNEL_NAME = 'EKKO_TS3_CHANNEL_NAME'
    TS3_CHANNEL_ID = 'EKKO_TS3_CHANNEL_ID'
    TS3_CHANNEL_PASSWORD = 'EKKO_TS3_CHANNEL_PASSWORD'
    TS3_SERVER_PASSWORD = 'EKKO_TS3_SERVER_PASSWORD'
    TS3_SERVER_PERMISSION_TOKEN = 'EKKO_TS3_SERVER_PERMISSION_TOKEN'

    EKKO_MANAGE_SERVER = 'EKKO_MANAGE_SERVER'
    EKKO_MANAGE_PORT = 'EKKO_MANAGE_PORT'

    TS3_DIRECTORY = 'EKKO_TS3_DIRECTORY'
    TS3_RUNSCRIPT = 'EKKO_TS3_RUNSCRIPT'
    EKKO_MEDIA_DIRECTORY = 'EKKO_MEDIA_DIRECTORY'
    DOCKER_EKKO_CLIENT_DIRECTORY = 'EKKO_DOCKER_EKKOCLIENT_DIRECTORY'

    DOCKER_DISABLE_AUTOREMOVE = 'EKKO_DOCKER_DISABLE_AUTOREMOVE'
    DOCKER_NETWORK_NAME = 'EKKO_DOCKER_NETWORK_NAME'

    DB_USERNAME = 'EKKO_DB_USERNAME'
    DB_HOST = 'EKKO_DB_HOST'
    DB_PASSWORD = 'EKKO_DB_PASSWORD'
    DB_DBNAME = 'EKKO_DB_DBNAME'

    EKKO_FIXTURES_PATH = 'EKKO_FIXTURES_PATH'

    LOG_LEVEL = 'EKKO_LOG_LEVEL'
    LOG_FORMAT = 'EKKO_LOG_FORMAT'
