
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-20T09:32:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8febd6b97ab7e8de9a0828df1730df9bdd94e1f0",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
