
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-15T19:33:40-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c66b4d300f3b53ab38d83ed82d8000460fb585c",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
