u"""
Copyright 2015-2017 Hermann Krumrey

This file is part of manga-dl.

manga-dl is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

manga-dl is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with manga-dl.  If not, see <http://www.gnu.org/licenses/>.
"""


class MangaPage(object):
    u"""
    Class that models a page in a Manga chapter
    """

    page_number = -1
    u"""
    The page's page number
    """

    image_url = u""
    u"""
    The URL to the page's image
    """

    page_name = u""
    u"""
    The page's name. Is normally generated by the get_page_name method
    """

    def __init__(self, page_number, image_url):
        u"""
        Initializes the Manga Page with a page number and an image URL

        :param page_number: the page number
        :param image_url: the image URL
        :return: None
        """
        self.page_number = page_number
        self.image_url = image_url

    def set_page_name(self, name):
        u"""
        Sets the page's name

        :param name: the name of the page
        :return: None
        """
        self.page_name = name

    def get_page_name(self):
        u"""
        Generates a Page name for this page based on the page number, or
        returns the page name previously set by the set_page_name method.

        :return: the page name as a string
        """
        return self.page_name if self.page_name != u"" \
            else u"Page " + unicode(self.page_number).zfill(3)
