# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python: 3.6

install:
  - sudo ./bootstrap-system.sh
  - sudo ./setup-pip.sh
  - sudo apt-get install -y libffi-dev libssl-dev pandoc nodejs
  # for coveralls and removing InsecurePlatformWarning
  - pipenv run pip install codecov coveralls pytest-cov requests[security]
  - make frontend-dev
  - make backend-dev

script:
  - make backend-checks
  - make frontend-lint
  - make frontend-build
  - make release
  - make test-unit
  - make test-coverage
  # - ./test-docker.sh

after_success:
  - coveralls
  - codecov

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: !!binary |
      TktFNXg2ZldIVHB6Y0FES0lwLzBLYU14NDJtM1B0eGF1NjJKMTBkR0h1dVoyU3BVUk9CVjNneVVx
      NFlBSnQyZEhBUXR2T21qTHJvQk5DK1JkOUlXVXk2S3FYS3RJR0RHU29xM2l3OG9BdHF2eVFTNEdX
      TERZUXBWOE9OUnVZRmphbXQrZnBYQWIzU0N0RldkaEEvaFBjV293Q3cvamZXcDVWbXpYaHJ4MHRt
      NlRlUFdZNGtJOXp3ZTJibWZDbHh0MnNpMEkwODBpZUllb1hxanVLcTFtVWhaUEFXZzFsWlpTby9l
      cWc2emp1K2lJMldnRklicHRCS1VIUWUvNjlSck5nNEVPMnErM01nSVJtZ1dZeENGblRURGtMcXVy
      ZVBZYjlxQ1lkWURDb0lrZUpEWGkvTFU4Nml5N2puMjYxMnlFOVUxazc1dUszM3FFUElkcithMTNx
      QXRlb1hxUDJPWnpEWnYxb2tIZno1SSt2UmtNOUU4NC8zTFdEa1RvRzBwekxXVWo5enBhbWpIeTFJ
      czRUbG1LVjZDTGZBOHFmREJQVU5ONzkxVmRia2pJTUp0OXpITDhmVy9VeHI1WGVRRjJMbFYvSDRD
      Q1hCYko2QXFzdm1YSWRYZnhpUFNzdWJYMURvb0s0QTZqczVJRlh5bTYybnhWbnVEQmM3SHpzejhn
      eGgwTDRteU9iQ0ZVQllBQ3ZWSWJHYmtlWXMveWZtV21QaVRDamZKV0JtbHFFa3dMdU5adnpGN0Mz
      VlFSN0NLK3hrWWs3OGJVaXhRQS9uVThpakZQRUp5K0d2UEhjb3lOYlhrZldvV3RGN0FTZmRXZDV1
      VUZQN3VnbnB0R05SZGJMZ3ZPVENEcGQrN2RqU2MzSDArT1oxVEhRWU1YWXArckNVZ3hjVVRSZDg9
  on:
    tags: true
    repo: Stibbons/dopplerr
