# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/vision/CalibrationMatrices.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.vision import CameraMatrix3x4_pb2 as rst_dot_vision_dot_CameraMatrix3x4__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/vision/CalibrationMatrices.proto',
  package='rst.vision',
  syntax='proto2',
  serialized_pb=_b('\n$rst/vision/CalibrationMatrices.proto\x12\nrst.vision\x1a rst/vision/CameraMatrix3x4.proto\"l\n\x13\x43\x61librationMatrices\x12)\n\x04left\x18\x01 \x02(\x0b\x32\x1b.rst.vision.CameraMatrix3x4\x12*\n\x05right\x18\x02 \x02(\x0b\x32\x1b.rst.vision.CameraMatrix3x4B\x19\x42\x17\x43\x61librationMatricesType')
  ,
  dependencies=[rst_dot_vision_dot_CameraMatrix3x4__pb2.DESCRIPTOR,])




_CALIBRATIONMATRICES = _descriptor.Descriptor(
  name='CalibrationMatrices',
  full_name='rst.vision.CalibrationMatrices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='rst.vision.CalibrationMatrices.left', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right', full_name='rst.vision.CalibrationMatrices.right', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=194,
)

_CALIBRATIONMATRICES.fields_by_name['left'].message_type = rst_dot_vision_dot_CameraMatrix3x4__pb2._CAMERAMATRIX3X4
_CALIBRATIONMATRICES.fields_by_name['right'].message_type = rst_dot_vision_dot_CameraMatrix3x4__pb2._CAMERAMATRIX3X4
DESCRIPTOR.message_types_by_name['CalibrationMatrices'] = _CALIBRATIONMATRICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrationMatrices = _reflection.GeneratedProtocolMessageType('CalibrationMatrices', (_message.Message,), dict(
  DESCRIPTOR = _CALIBRATIONMATRICES,
  __module__ = 'rst.vision.CalibrationMatrices_pb2'
  # @@protoc_insertion_point(class_scope:rst.vision.CalibrationMatrices)
  ))
_sym_db.RegisterMessage(CalibrationMatrices)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\027CalibrationMatricesType'))
# @@protoc_insertion_point(module_scope)
