redis:
  image: redis
  ports:
    - "6379:6379"

mongo:
  image: mongo
  ports:
    - "27017:27017"

crawler-manager:
  build: .
  ports:
    - "6800:6800"
  links:
    - redis:localhost
    - mongo:localhost