# Conda environment specification
# 1. to export (recommend editing before checking in to git):
#    conda env export > .environment.yml
# 2. to import/create a copy of the environment:
#    conda env create -f .environment.yml
name: smif
channels:
- conda-forge
- defaults
dependencies:
- conda-forge::appdirs=1.4.3=py35_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py35_0
- conda-forge::click=6.7=py35_0
- conda-forge::click-plugins=1.0.3=py35_0
- conda-forge::cligj=0.4.0=py35_0
- conda-forge::colorama=0.3.7=py35_0
- conda-forge::curl=7.52.1
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.11=py35_0
- conda-forge::expat=2.1.0
- conda-forge::fiona=1.7.4=np111py35_0
- conda-forge::freetype=2.7
- conda-forge::freexl=1.0.2
- conda-forge::gdal=2.1.3
- conda-forge::geos=3.5.1
- conda-forge::hdf4=4.2.12
- conda-forge::hdf5=1.8.17
- conda-forge::icu=58.1
- conda-forge::ipython=5.3.0=py35_0
- conda-forge::ipython_genutils=0.2.0=py35_0
- conda-forge::jpeg=9b
- conda-forge::kealib=1.4.6
- conda-forge::libiconv=1.14
- conda-forge::libnetcdf=4.4.1.1
- conda-forge::libpng=1.6.28
- conda-forge::libpq=9.5.4
- conda-forge::libspatialindex=1.8.5
- conda-forge::libspatialite=4.3.0a
- conda-forge::libtiff=4.0.6
- conda-forge::libxml2=2.9.4
- conda-forge::matplotlib=2.0.0=np111py35_2
- conda-forge::mpmath=0.19=py35_2
- conda-forge::munch=2.1.0=py35_0
- conda-forge::networkx=1.11=py35_0
- conda-forge::nose=1.3.7=py35_2
- conda-forge::openjpeg=2.1.2
- conda-forge::openssl=1.0.2h
- conda-forge::pandas=0.19.2=np111py35_1
- conda-forge::pcre=8.39
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pint=0.8.1=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::ply=3.9=py35_0
- conda-forge::proj4=4.9.3
- conda-forge::prompt_toolkit=1.0.13=py35_0
- conda-forge::py=1.4.33=py35_0
- conda-forge::pygments=2.2.0=py35_0
- conda-forge::pyomo=5.1.1=py35_0
- conda-forge::pyomo.extras=3.2=py35_0
- conda-forge::pyparsing=2.2.0=py35_0
- conda-forge::pyqt=4.11.4=py35_2
- conda-forge::pyro4=4.43=py35_2
- conda-forge::pytest=3.0.7=py35_0
- conda-forge::python=3.5.3=1
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.10=py35_0
- conda-forge::pyutilib=5.4.1=py35_0
- conda-forge::pyyaml=3.12=py35_0
- conda-forge::qt=4.8.7
- conda-forge::rtree=0.8.3=py35_0
- conda-forge::serpent=1.12=py35_0
- conda-forge::setuptools=33.1.0=py35_0
- conda-forge::shapely=1.5.17=np111py35_2
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_1
- conda-forge::six=1.10.0=py35_1
- conda-forge::sqlite=3.13.0
- conda-forge::sympy=1.0=py35_0
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.2=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::xerces-c=3.1.4
- conda-forge::xlrd=1.0.0=py35_1
- conda-forge::yaml=0.1.6
- conda-forge::zlib=1.2.11
- et_xmlfile=1.0.1=py35_0
- fastcache=1.0.2=py35_1
- jdcal=1.3=py35_0
- mkl=2017.0.1=0
- numpy=1.11.3=py35_0
- openpyxl=2.4.1=py35_0
- pymysql=0.7.9=py35_0
- pyodbc=3.0.10=py35_1
- scipy=0.19.0=np111py35_0
- pip:
  - aspy.yaml==0.2.2
  - astroid==1.4.9
  - behave==1.2.5
  - cached-property==1.3.0
  - coverage==4.3.4
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - isodate==0.5.4
  - isort==4.2.5
  - jsonschema==2.6.0
  - lazy-object-proxy==1.2.2
  - mccabe==0.6.1
  - nodeenv==1.1.2
  - parse==1.8.0
  - parse-type==0.3.4
  - pre-commit==0.13.3
  - prompt-toolkit==1.0.13
  - pylint==1.6.5
  - pytest-cov==2.4.0
  - virtualenv==15.1.0
  - wrapt==1.10.10
