# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeconductor_digitalocean', '0003_update_ip_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='droplet',
            name='region_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
