dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"

language: python

matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: pypy2.7-5.8.0
    env: TOXENV=pypy

install:
- pip install tox

script:
- tox

before_install:
- pip install codecov

after_success:
- tox -e coverage-report
- codecov

notifications:
  email: false

deploy:
  provider: pypi
  user: spotify_alf
  password:
    secure: vl9eN23gDrYmsYLmgtZ0SGx0mySXl/p9TEM1Vj34C2lq2j8Iaz9O4HOhRq4aWBHoWfP5CsCcmFn3giJvFCJsSLErub4YfC2hGTn3XTSodgABz4uClgxiKjIgmbhDTMLRMnFshpxHQ6a7ps71YsCq0o+95AGP+bmJkflZ/syyfYmMPLDvWXMZ1baaV/vH/LSkr+48em6jHh18wjV6uKDM7ttqfNRq51G4zoXdNSfmi9RkppXeBbC2ljYjqNmlWZYAD5yx762zCZGaMjE/tjp1SR+SfGFQrXlv7bjtSsjaTlPC60wkNBc/DqV1SVow/NBoaGMRIWUPcVeIlMtDKN2f7eraZj141iI+puCKfBL8qqI9KYSNxElIsLW/IFGtdnyvqKwntBfDndizD8WPRH9VFWbI3QyFMCybYmD4oPcez2mhnnd5Pb0pA+CrVN/lgdBz2ENplEOgWEuxDJCA05hjxVXRrJ92WiHI+F9ui8mUKejYp9O4j3GddZ4Ocsnx9MTtn8pDTtArkGWPK0MX5RIiBwLKvsIGbYLcKF7C9PkRTz6LYN8tSU//aw8KuWNMYOACC1kapxW0OqJjCdcL+kynFmA1DT8JTdwzjdRJfw6IrCntausToczOFO1ME+U8cepsYA74uRnA8wsAHfq2fnJx/jOuNcZIaLsRUcv9cCdcUVk=
  on:
    tags: true
