# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/monitoring/ProcessAnomalyCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.monitoring import ProcessAnomaly_pb2 as rst_dot_monitoring_dot_ProcessAnomaly__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/monitoring/ProcessAnomalyCollection.proto',
  package='rst.monitoring',
  syntax='proto2',
  serialized_pb=_b('\n-rst/monitoring/ProcessAnomalyCollection.proto\x12\x0erst.monitoring\x1a#rst/monitoring/ProcessAnomaly.proto\"K\n\x18ProcessAnomalyCollection\x12/\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x1e.rst.monitoring.ProcessAnomalyB\x1e\x42\x1cProcessAnomalyCollectionType')
  ,
  dependencies=[rst_dot_monitoring_dot_ProcessAnomaly__pb2.DESCRIPTOR,])




_PROCESSANOMALYCOLLECTION = _descriptor.Descriptor(
  name='ProcessAnomalyCollection',
  full_name='rst.monitoring.ProcessAnomalyCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.monitoring.ProcessAnomalyCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=177,
)

_PROCESSANOMALYCOLLECTION.fields_by_name['element'].message_type = rst_dot_monitoring_dot_ProcessAnomaly__pb2._PROCESSANOMALY
DESCRIPTOR.message_types_by_name['ProcessAnomalyCollection'] = _PROCESSANOMALYCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessAnomalyCollection = _reflection.GeneratedProtocolMessageType('ProcessAnomalyCollection', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSANOMALYCOLLECTION,
  __module__ = 'rst.monitoring.ProcessAnomalyCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.monitoring.ProcessAnomalyCollection)
  ))
_sym_db.RegisterMessage(ProcessAnomalyCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\034ProcessAnomalyCollectionType'))
# @@protoc_insertion_point(module_scope)
