# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/robot/JointState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.kinematics import JointAngles_pb2 as rst_dot_kinematics_dot_JointAngles__pb2
from rst.kinematics import JointVelocities_pb2 as rst_dot_kinematics_dot_JointVelocities__pb2
from rst.dynamics import JointTorques_pb2 as rst_dot_dynamics_dot_JointTorques__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/robot/JointState.proto',
  package='rst.robot',
  syntax='proto2',
  serialized_pb=_b('\n\x1arst/robot/JointState.proto\x12\trst.robot\x1a rst/kinematics/JointAngles.proto\x1a$rst/kinematics/JointVelocities.proto\x1a\x1frst/dynamics/JointTorques.proto\"\x9b\x01\n\nJointState\x12+\n\x06\x61ngles\x18\x01 \x02(\x0b\x32\x1b.rst.kinematics.JointAngles\x12\x33\n\nvelocities\x18\x02 \x02(\x0b\x32\x1f.rst.kinematics.JointVelocities\x12+\n\x07torques\x18\x03 \x02(\x0b\x32\x1a.rst.dynamics.JointTorquesB\x10\x42\x0eJointStateType')
  ,
  dependencies=[rst_dot_kinematics_dot_JointAngles__pb2.DESCRIPTOR,rst_dot_kinematics_dot_JointVelocities__pb2.DESCRIPTOR,rst_dot_dynamics_dot_JointTorques__pb2.DESCRIPTOR,])




_JOINTSTATE = _descriptor.Descriptor(
  name='JointState',
  full_name='rst.robot.JointState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angles', full_name='rst.robot.JointState.angles', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocities', full_name='rst.robot.JointState.velocities', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='torques', full_name='rst.robot.JointState.torques', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=302,
)

_JOINTSTATE.fields_by_name['angles'].message_type = rst_dot_kinematics_dot_JointAngles__pb2._JOINTANGLES
_JOINTSTATE.fields_by_name['velocities'].message_type = rst_dot_kinematics_dot_JointVelocities__pb2._JOINTVELOCITIES
_JOINTSTATE.fields_by_name['torques'].message_type = rst_dot_dynamics_dot_JointTorques__pb2._JOINTTORQUES
DESCRIPTOR.message_types_by_name['JointState'] = _JOINTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JointState = _reflection.GeneratedProtocolMessageType('JointState', (_message.Message,), dict(
  DESCRIPTOR = _JOINTSTATE,
  __module__ = 'rst.robot.JointState_pb2'
  # @@protoc_insertion_point(class_scope:rst.robot.JointState)
  ))
_sym_db.RegisterMessage(JointState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\016JointStateType'))
# @@protoc_insertion_point(module_scope)
