dist: trusty

language: python
python:
  - "2.7"
  - "3.6"

env:
  fast_finish: true

install:
  # The plugin for the setup tools with git and git archives has to be installed manually
  # in order that as the pip install runs it can do the git discovery for tags etc
  #
  - pip install -e .
  - pip install pep8

script:
  - nosetests -v 
  - pep8 --show-source .
  - python setup.py sdist

deploy:
  provider: pypi
  distributions: "sdist"
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
