
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2017-11-05T22:23:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c3d911a8b759e52b864b00afde35a54538afbe5",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
