# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Nov 23 22:32:55 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(729, 796)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 701, 24))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.line_2 = QtGui.QFrame(self.layoutWidget_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_7.addWidget(self.line_2, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 460, 701, 24))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.line_4 = QtGui.QFrame(self.layoutWidget_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_8.addWidget(self.line_4, 2, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 1, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 701, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 1, 0, 1, 1)
        self.textBrowser_SectionProperties = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_SectionProperties.setGeometry(QtCore.QRect(240, 40, 261, 161))
        self.textBrowser_SectionProperties.setObjectName(_fromUtf8("textBrowser_SectionProperties"))
        self.pushButton_apllytosec = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apllytosec.setGeometry(QtCore.QRect(10, 140, 191, 23))
        self.pushButton_apllytosec.setObjectName(_fromUtf8("pushButton_apllytosec"))
        self.textBrowser_Results = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_Results.setGeometry(QtCore.QRect(10, 520, 481, 191))
        self.textBrowser_Results.setObjectName(_fromUtf8("textBrowser_Results"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(24, 40, 40, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_SectionName = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_SectionName.setEnabled(False)
        self.lineEdit_SectionName.setGeometry(QtCore.QRect(70, 40, 151, 20))
        self.lineEdit_SectionName.setObjectName(_fromUtf8("lineEdit_SectionName"))
        self.pushButton_BrowseSection = QtGui.QPushButton(self.centralwidget)
        self.pushButton_BrowseSection.setGeometry(QtCore.QRect(200, 80, 16, 21))
        self.pushButton_BrowseSection.setObjectName(_fromUtf8("pushButton_BrowseSection"))
        self.listWidget_loadcases = QtGui.QListWidget(self.centralwidget)
        self.listWidget_loadcases.setGeometry(QtCore.QRect(10, 310, 611, 141))
        self.listWidget_loadcases.setObjectName(_fromUtf8("listWidget_loadcases"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(10, 290, 561, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.lineEdit_M_zEd = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_M_zEd.setGeometry(QtCore.QRect(250, 259, 68, 20))
        self.lineEdit_M_zEd.setObjectName(_fromUtf8("lineEdit_M_zEd"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 240, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_V_zEd = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_V_zEd.setGeometry(QtCore.QRect(410, 259, 68, 20))
        self.lineEdit_V_zEd.setObjectName(_fromUtf8("lineEdit_V_zEd"))
        self.lineEdit_V_yEd = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_V_yEd.setGeometry(QtCore.QRect(330, 259, 68, 20))
        self.lineEdit_V_yEd.setObjectName(_fromUtf8("lineEdit_V_yEd"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 240, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(330, 240, 61, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_Resistance = QtGui.QPushButton(self.centralwidget)
        self.pushButton_Resistance.setGeometry(QtCore.QRect(110, 490, 90, 23))
        self.pushButton_Resistance.setObjectName(_fromUtf8("pushButton_Resistance"))
        self.pushButton_CheckSection = QtGui.QPushButton(self.centralwidget)
        self.pushButton_CheckSection.setGeometry(QtCore.QRect(10, 490, 90, 23))
        self.pushButton_CheckSection.setObjectName(_fromUtf8("pushButton_CheckSection"))
        self.lineEdit_N_Ed = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_N_Ed.setGeometry(QtCore.QRect(90, 259, 67, 20))
        self.lineEdit_N_Ed.setObjectName(_fromUtf8("lineEdit_N_Ed"))
        self.lineEdit_M_yEd = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_M_yEd.setGeometry(QtCore.QRect(170, 259, 68, 20))
        self.lineEdit_M_yEd.setObjectName(_fromUtf8("lineEdit_M_yEd"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(490, 241, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 240, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 240, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_T_Ed = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_T_Ed.setEnabled(False)
        self.lineEdit_T_Ed.setGeometry(QtCore.QRect(490, 260, 68, 20))
        self.lineEdit_T_Ed.setObjectName(_fromUtf8("lineEdit_T_Ed"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(24, 80, 80, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_SectionFigure = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_SectionFigure.setGeometry(QtCore.QRect(110, 80, 81, 20))
        self.lineEdit_SectionFigure.setObjectName(_fromUtf8("lineEdit_SectionFigure"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(20, 110, 65, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(510, 40, 211, 161))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.listWidget_typelist = QtGui.QListWidget(self.centralwidget)
        self.listWidget_typelist.setGeometry(QtCore.QRect(510, 550, 81, 141))
        self.listWidget_typelist.setObjectName(_fromUtf8("listWidget_typelist"))
        self.listWidget_sectnamelist = QtGui.QListWidget(self.centralwidget)
        self.listWidget_sectnamelist.setGeometry(QtCore.QRect(600, 550, 111, 141))
        self.listWidget_sectnamelist.setObjectName(_fromUtf8("listWidget_sectnamelist"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(490, 490, 20, 231))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_info_2 = QtGui.QLabel(self.centralwidget)
        self.label_info_2.setGeometry(QtCore.QRect(10, 739, 271, 21))
        self.label_info_2.setObjectName(_fromUtf8("label_info_2"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 720, 701, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.progressBar_FindSections = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_FindSections.setGeometry(QtCore.QRect(530, 740, 181, 16))
        self.progressBar_FindSections.setProperty("value", 0)
        self.progressBar_FindSections.setTextVisible(False)
        self.progressBar_FindSections.setObjectName(_fromUtf8("progressBar_FindSections"))
        self.lineEdit_Name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_Name.setGeometry(QtCore.QRect(10, 259, 67, 20))
        self.lineEdit_Name.setObjectName(_fromUtf8("lineEdit_Name"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_loadAddCase = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadAddCase.setGeometry(QtCore.QRect(560, 260, 75, 23))
        self.pushButton_loadAddCase.setObjectName(_fromUtf8("pushButton_loadAddCase"))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(630, 300, 86, 170))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_loadSeletedON = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadSeletedON.setObjectName(_fromUtf8("pushButton_loadSeletedON"))
        self.verticalLayout_2.addWidget(self.pushButton_loadSeletedON)
        self.pushButton_loadSeletedOFF = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadSeletedOFF.setObjectName(_fromUtf8("pushButton_loadSeletedOFF"))
        self.verticalLayout_2.addWidget(self.pushButton_loadSeletedOFF)
        self.pushButton_loadAllON = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadAllON.setObjectName(_fromUtf8("pushButton_loadAllON"))
        self.verticalLayout_2.addWidget(self.pushButton_loadAllON)
        self.pushButton_loadAllOFF = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadAllOFF.setObjectName(_fromUtf8("pushButton_loadAllOFF"))
        self.verticalLayout_2.addWidget(self.pushButton_loadAllOFF)
        self.pushButton_loadDelAll = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadDelAll.setObjectName(_fromUtf8("pushButton_loadDelAll"))
        self.verticalLayout_2.addWidget(self.pushButton_loadDelAll)
        self.pushButton_loadDelSelected = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_loadDelSelected.setObjectName(_fromUtf8("pushButton_loadDelSelected"))
        self.verticalLayout_2.addWidget(self.pushButton_loadDelSelected)
        self.pushButton_loadEditSelected = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadEditSelected.setGeometry(QtCore.QRect(640, 260, 75, 23))
        self.pushButton_loadEditSelected.setObjectName(_fromUtf8("pushButton_loadEditSelected"))
        self.pushButton_zoom_in = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_in.setGeometry(QtCore.QRect(520, 50, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_in.setPalette(palette)
        self.pushButton_zoom_in.setObjectName(_fromUtf8("pushButton_zoom_in"))
        self.pushButton_zoom_out = QtGui.QPushButton(self.centralwidget)
        self.pushButton_zoom_out.setGeometry(QtCore.QRect(520, 80, 21, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_zoom_out.setPalette(palette)
        self.pushButton_zoom_out.setObjectName(_fromUtf8("pushButton_zoom_out"))
        self.comboBox_SteelGrade = QtGui.QComboBox(self.centralwidget)
        self.comboBox_SteelGrade.setGeometry(QtCore.QRect(110, 110, 60, 20))
        self.comboBox_SteelGrade.setObjectName(_fromUtf8("comboBox_SteelGrade"))
        self.comboBox_sectiongroups = QtGui.QComboBox(self.centralwidget)
        self.comboBox_sectiongroups.setGeometry(QtCore.QRect(510, 490, 201, 22))
        self.comboBox_sectiongroups.setMaxVisibleItems(20)
        self.comboBox_sectiongroups.setObjectName(_fromUtf8("comboBox_sectiongroups"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(510, 520, 201, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_18 = QtGui.QLabel(self.widget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.comboBox_Find_from = QtGui.QComboBox(self.widget)
        self.comboBox_Find_from.setEnabled(True)
        self.comboBox_Find_from.setMaximumSize(QtCore.QSize(61, 16777215))
        self.comboBox_Find_from.setObjectName(_fromUtf8("comboBox_Find_from"))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.comboBox_Find_from.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_Find_from)
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout.addWidget(self.label_19)
        self.comboBox_Find_to = QtGui.QComboBox(self.widget)
        self.comboBox_Find_to.setEnabled(True)
        self.comboBox_Find_to.setMaximumSize(QtCore.QSize(71, 16777215))
        self.comboBox_Find_to.setObjectName(_fromUtf8("comboBox_Find_to"))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.comboBox_Find_to.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_Find_to)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(510, 700, 201, 25))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_FindSections = QtGui.QPushButton(self.widget1)
        self.pushButton_FindSections.setObjectName(_fromUtf8("pushButton_FindSections"))
        self.horizontalLayout_2.addWidget(self.pushButton_FindSections)
        self.pushButton_ApllySelected = QtGui.QPushButton(self.widget1)
        self.pushButton_ApllySelected.setObjectName(_fromUtf8("pushButton_ApllySelected"))
        self.horizontalLayout_2.addWidget(self.pushButton_ApllySelected)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setEnabled(False)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout_STRUTHON_CENCRERE_MONO = QtGui.QAction(MainWindow)
        self.actionAbout_STRUTHON_CENCRERE_MONO.setObjectName(_fromUtf8("actionAbout_STRUTHON_CENCRERE_MONO"))
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_Find_from.setCurrentIndex(0)
        self.comboBox_Find_to.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "STRUTHON.STEEL.MONO.SECTION", None))
        self.label_16.setText(_translate("MainWindow", "Section properties", None))
        self.label_17.setText(_translate("MainWindow", "Results", None))
        self.label_15.setText(_translate("MainWindow", "Section loads", None))
        self.pushButton_apllytosec.setText(_translate("MainWindow", "Apply to section ", None))
        self.label_28.setText(_translate("MainWindow", "Name - ", None))
        self.lineEdit_SectionName.setText(_translate("MainWindow", "Sec_1", None))
        self.pushButton_BrowseSection.setText(_translate("MainWindow", "..", None))
        self.label_35.setText(_translate("MainWindow", "No.,  Name,      N_Ed[kN],   M_yEd[kNm],   M_zEd[kNm],    V_yEd[kN],    V_zEd[kN],    T_Ed[kNm],    active[]", None))
        self.lineEdit_M_zEd.setText(_translate("MainWindow", "0.0", None))
        self.label_8.setText(_translate("MainWindow", "M_zEd[kNm]", None))
        self.lineEdit_V_zEd.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_V_yEd.setText(_translate("MainWindow", "0.0", None))
        self.label_10.setText(_translate("MainWindow", "V_zEd[kNm]", None))
        self.label_12.setText(_translate("MainWindow", "V_yEd[kNm]", None))
        self.pushButton_Resistance.setText(_translate("MainWindow", "RESISTANCE", None))
        self.pushButton_CheckSection.setText(_translate("MainWindow", "CHECK SECTION", None))
        self.lineEdit_N_Ed.setText(_translate("MainWindow", "0.0", None))
        self.lineEdit_M_yEd.setText(_translate("MainWindow", "0.0", None))
        self.label_14.setText(_translate("MainWindow", "T_Ed[kNm]", None))
        self.label_4.setText(_translate("MainWindow", "N_Ed[kN]", None))
        self.label_3.setText(_translate("MainWindow", "M_yEd[kNm]", None))
        self.lineEdit_T_Ed.setText(_translate("MainWindow", "0.0", None))
        self.label_26.setText(_translate("MainWindow", "Section - ", None))
        self.label_27.setText(_translate("MainWindow", "Steel grade - ", None))
        self.label_info_2.setText(_translate("MainWindow", "StruthonSteelMonoSection v0.1 ( www.struthon.org)                                                                                   ", None))
        self.lineEdit_Name.setText(_translate("MainWindow", "Noname", None))
        self.label_5.setText(_translate("MainWindow", "Name", None))
        self.pushButton_loadAddCase.setText(_translate("MainWindow", "Add loadcase", None))
        self.pushButton_loadSeletedON.setText(_translate("MainWindow", "Selected ON", None))
        self.pushButton_loadSeletedOFF.setText(_translate("MainWindow", "Selected OFF", None))
        self.pushButton_loadAllON.setText(_translate("MainWindow", "All ON", None))
        self.pushButton_loadAllOFF.setText(_translate("MainWindow", "All OFF", None))
        self.pushButton_loadDelAll.setText(_translate("MainWindow", "Delete all", None))
        self.pushButton_loadDelSelected.setText(_translate("MainWindow", "Delete selected", None))
        self.pushButton_loadEditSelected.setText(_translate("MainWindow", "Edit selected", None))
        self.pushButton_zoom_in.setText(_translate("MainWindow", "+", None))
        self.pushButton_zoom_out.setText(_translate("MainWindow", "-", None))
        self.label_18.setText(_translate("MainWindow", "Capacity factor", None))
        self.comboBox_Find_from.setItemText(0, _translate("MainWindow", "0.0", None))
        self.comboBox_Find_from.setItemText(1, _translate("MainWindow", "0.1", None))
        self.comboBox_Find_from.setItemText(2, _translate("MainWindow", "0.3", None))
        self.comboBox_Find_from.setItemText(3, _translate("MainWindow", "0.4", None))
        self.comboBox_Find_from.setItemText(4, _translate("MainWindow", "0.5", None))
        self.comboBox_Find_from.setItemText(5, _translate("MainWindow", "0.6", None))
        self.comboBox_Find_from.setItemText(6, _translate("MainWindow", "0.7", None))
        self.comboBox_Find_from.setItemText(7, _translate("MainWindow", "0.8", None))
        self.comboBox_Find_from.setItemText(8, _translate("MainWindow", "0.9", None))
        self.comboBox_Find_from.setItemText(9, _translate("MainWindow", "1.0", None))
        self.label_19.setText(_translate("MainWindow", "to", None))
        self.comboBox_Find_to.setItemText(0, _translate("MainWindow", "0.1", None))
        self.comboBox_Find_to.setItemText(1, _translate("MainWindow", "0.2", None))
        self.comboBox_Find_to.setItemText(2, _translate("MainWindow", "0.3", None))
        self.comboBox_Find_to.setItemText(3, _translate("MainWindow", "0.4", None))
        self.comboBox_Find_to.setItemText(4, _translate("MainWindow", "0.5", None))
        self.comboBox_Find_to.setItemText(5, _translate("MainWindow", "0.6", None))
        self.comboBox_Find_to.setItemText(6, _translate("MainWindow", "0.7", None))
        self.comboBox_Find_to.setItemText(7, _translate("MainWindow", "0.8", None))
        self.comboBox_Find_to.setItemText(8, _translate("MainWindow", "0.9", None))
        self.comboBox_Find_to.setItemText(9, _translate("MainWindow", "1.0", None))
        self.pushButton_FindSections.setText(_translate("MainWindow", "FIND SECTIONS", None))
        self.pushButton_ApllySelected.setText(_translate("MainWindow", "Apply selected", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionAbout_STRUTHON_CENCRERE_MONO.setText(_translate("MainWindow", "About STRUTHON CENCRERE MONO", None))

