
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-28T18:00:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3083fb3c0adb51bd35c77be9758169b9b70bf993",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
