# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeconductor_aws', '0004_remove_volume_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='size_backend_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
