# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0002_auto_20171017_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectvendor',
            name='slug',
        ),
        migrations.AddField(
            model_name='objectvariant',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectvariant',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterUniqueTogether(
            name='objectmodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='objectmodel',
            name='slug',
        ),
    ]
