# coding: utf-8
# Generated by setup.py for PyCBC on 2017-11-18 18:47:42 +0000.

version = '1.8.2'
date = '2017-11-18 17:39:21 +0000'
release = True
last_release = '1.8.2'

git_hash = '811e3d4d7e9c599b4047accdba569a990b54ee78'
git_branch = 'None'
git_tag = 'v1.8.2'
git_author = 'Alex Nitz <alex.nitz@gmail.com>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Travis CI User <travis@example.org>'
git_build_date = '2017-11-18 18:47:42 +0000'
git_verbose_msg = """Branch: None
Tag: v1.8.2
Id: 811e3d4d7e9c599b4047accdba569a990b54ee78
Builder: Travis CI User <travis@example.org>
Build date: 2017-11-18 18:47:42 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
