language: python

python:
  - "3.5"

env:
  - TOXENV=py35
  - TOXENV=py34

matrix:
  fast_finish: true

before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo apt-get install -y git-flow python-enchant

install:
  - pip install -r requirements/local.txt coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - git --version

script:
  - tox -e $TOXENV

jobs:
  include:
    - stage: make
      script:
          - which python
          - tox --version
          - pwd
          - ls -la
          - make
          - make bump
          - make lint
          - make test
          - make test-all
          - make coverage
          - make dist
          - make install
          - make docs
          # Lint again after docs generation
          - make lint
          - make clean

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov -e TOX_ENV
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
