
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-24T06:03:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2aa0bd1c0188cddeafa36545a8589e4bcb020ad",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
