# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectgeneration',
            name='finish_production',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Finish production'),
        ),
    ]
