# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0006_auto_20171027_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectfilter',
            name='tags_group_2',
        ),
        migrations.RemoveField(
            model_name='objectfilter',
            name='tags_group_3',
        ),
    ]
