# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0007_auto_20171101_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectfilter',
            old_name='tags_group_1',
            new_name='tags',
        ),
    ]
