# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 12:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0008_auto_20171101_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfilter',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='Tags'),
        ),
    ]
