# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcart_product_finder', '0012_productfinderformpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfinderformpluginmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
    ]
