
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a08c14fb757379ec84fed8d75eb02f0d21011560",
 "version": "1.1.post8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
