
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-10-24T00:54:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c1bee2fba69a7d9296166e36203122e7dbce483",
 "version": "0.21.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
