language: python

python:
  - '2.7'
  - '3.4'

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - nosetests
  - flake8

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: fZxfMePJQroeiLQb+lmpNiEEMvRONOVt4yTQY8CmemyVMOe4TVZUfsBzCMa7eZkUaFZuHfNaUo/4Jmhn15EruzGhqBLRe5fpuFxFqJqDJ7ZmPMTRBIMKUsRuYrG6vc9YmG8CLfLvxwG8OUoLzND+rz+QwWaFruFeDlkCN3xMpzRHcdopcKlKoKwUJCkPzqEm0qeziTsRNixLbrBHzfr+FY96FDclE2GDywUBCacPzwP+R9QwPKU74NevlD+MazP/bYcZHY8DKDQ2X4L7NSr/8osJswVvCCoOqqqFPsPLaVzhDLU1hvTSW44K3hUSlRmKWzmdfFutkPix4Zrge9JYzTOodV921WgFLSsSPcpwEoRMZM21hoFhO6PThd9ag33z1rUxXzAJxBYfjM5OP+2g6gqWDptyJp8OgdqjzoCKFsXBrINf+vb+Ossdtl2+W1fzBjHlV9D8t6gf7ekJZmTAKzfYcvrRc++gnZwlwmPWrr5qBUSxT9SEqln7L/u4RbHxZdAOzYivPBvrL1ncdwUx9kvzbelr1wolc0aszodRgx8S7aWZ7V4CbuE6LpNkRREJ+EY71MYInpCRO81XabAIEG7T7i11ZkNexxQAe5Mafy/nSw5cGWirIAcLEO7WU3tSd5rteP7hgp28VJ9XfGZPwH9Q1FqiNMpKk+Db6PwplDE=
  on:
    tags: true
    python: 3.4
    distributions: sdist bdist_wheel
    repo: internap/python-ubersmithclient
