
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-06T10:53:05-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c38e64cab820025a4f41dd5577b2d424fcda89fe",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
