# coding: utf-8

"""
    stylelens-search

    This is a API document for Image search on fashion items\"

    OpenAPI spec version: 0.0.1
    Contact: devops@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import stylelens_search
from stylelens_search.rest import ApiException
from stylelens_search.models.image_search_response_data import ImageSearchResponseData


class TestImageSearchResponseData(unittest.TestCase):
    """ ImageSearchResponseData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageSearchResponseData(self):
        """
        Test ImageSearchResponseData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = stylelens_search.models.image_search_response_data.ImageSearchResponseData()
        pass


if __name__ == '__main__':
    unittest.main()
