# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/xml/XOPs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.xml import XOP_pb2 as rst_dot_xml_dot_XOP__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/xml/XOPs.proto',
  package='rst.xml',
  syntax='proto2',
  serialized_pb=_b('\n\x12rst/xml/XOPs.proto\x12\x07rst.xml\x1a\x11rst/xml/XOP.proto\"\"\n\x04XOPs\x12\x1a\n\x04xops\x18\x01 \x03(\x0b\x32\x0c.rst.xml.XOPB\nB\x08XOPsType')
  ,
  dependencies=[rst_dot_xml_dot_XOP__pb2.DESCRIPTOR,])




_XOPS = _descriptor.Descriptor(
  name='XOPs',
  full_name='rst.xml.XOPs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xops', full_name='rst.xml.XOPs.xops', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=84,
)

_XOPS.fields_by_name['xops'].message_type = rst_dot_xml_dot_XOP__pb2._XOP
DESCRIPTOR.message_types_by_name['XOPs'] = _XOPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XOPs = _reflection.GeneratedProtocolMessageType('XOPs', (_message.Message,), dict(
  DESCRIPTOR = _XOPS,
  __module__ = 'rst.xml.XOPs_pb2'
  # @@protoc_insertion_point(class_scope:rst.xml.XOPs)
  ))
_sym_db.RegisterMessage(XOPs)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\010XOPsType'))
# @@protoc_insertion_point(module_scope)
