
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-15T15:12:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5954a149cd6f82f812ed9b2df38027c0f925bbe6",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
