language: python
python:
  - 3.5
  - 3.6
install:
  - pip install --only-binary=numpy,scipy,pandas pandas flake8 pytest
script:
  - flake8
  - python setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: davis.kirkendall
  password:
    secure: QDs9Cq2z+kXtJosfdKda470EnZy9HJpC40qAABuGgKk7z43NCvoRcAYkMnnx1GlwCHwj4Ta3ZVu1oXc1AH1eWGmVzPW/xx1752HjMh1EzRZu/2Pzz2FqqoJKTxJdkRXRZNLJCEvLj9vGbDfzF9P8R2Lk2286F9meACaS9UxdcgzkgiRtkltDaf5tcE4MGoO6IXc6xduN3a3wbuGZZC3KGAiUD4322KNwkmNgGHx3L5PI8qZx3KZXwA5MY82NlKSIDTt7JvnEmXO2i5Q3+a6I7vaGZIGmgoLDPWvXkKUkUbz6qkmJRDDdFA7pkmQ2Bx2ANAO4KfYlyiPCZK4kRA3bRFa2dtug+RdLsYj9F4p95tkNd3kMqJQogvfWWShR7T0fOvMqVYZLepcGmYUG7SOLanNhjPzd+UlXDW2rXaZMatimd0twQRqnEaB1lVJTkAG9NgCjh00yQdFO+jANp9kA+pysDYBlFCzOzDFqzbv4culcwbqwamz/IiLpL7GC2WV3hVI0YyQJ9Exs2W9If+Mz2NVmIOsNORG4WEkv1TkqrZuPY77sya3cMx9AIftdVwUce5sLl6XpOkIlNlAstXTNrdhRpVOV5okFv0qZa1fcV4b9JOxDOd2oTNnQmDb4cqLyK1SwfCSfBAoRXUlMIAkgB8hL0AscV+xBO5aUPTtF6ss=
  on:
    tags: true
