
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-11T20:16:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "37ef90cd4df5b14bb93fc18dbeab2a6b81e0ba9d",
 "version": "0.1.7b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
