
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-20T14:46:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc5aa82fe17c526323f236bf0adbeda1edb86e51",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
