
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-20T17:43:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf36857fa5120fd6e22b65d45e839cc0120d025d",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
