
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-19T11:50:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c69854eb45d4609d1f023353e3273801ccdd5f0f",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
