# coding: utf-8

"""
    Haplotype Frequency Curation Service

    Allows to store and return haplotype frequency data

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.access_data import AccessData
from .models.cohort_data import CohortData
from .models.error import Error
from .models.frequency_error import FrequencyError
from .models.genotype import Genotype
from .models.genotype_list import GenotypeList
from .models.genotype_method import GenotypeMethod
from .models.hf_curation_list_response import HFCurationListResponse
from .models.hf_curation_request import HFCurationRequest
from .models.hf_curation_response import HFCurationResponse
from .models.haplotype_frequency import HaplotypeFrequency
from .models.haplotype_frequency_data import HaplotypeFrequencyData
from .models.label import Label
from .models.label_data import LabelData
from .models.label_list import LabelList
from .models.license import License
from .models.method import Method
from .models.method_data import MethodData
from .models.method_list import MethodList
from .models.population_data import PopulationData
from .models.population_request import PopulationRequest
from .models.population_response import PopulationResponse
from .models.population_submission_data import PopulationSubmissionData
from .models.population_submission_response import PopulationSubmissionResponse
from .models.quality import Quality
from .models.resolution_data import ResolutionData
from .models.resolution_info import ResolutionInfo
from .models.scope_data import ScopeData
from .models.scope_element import ScopeElement

# import apis into sdk package
from .apis.default_api import DefaultApi
from .apis.population_api_api import PopulationAPIApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
