
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-01T12:10:59-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f60e6e51b90def37bbbf07978294e63b14ee82f1",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
