
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2f0ce6cb2c4a0027a55c51434ab84cb9419c2b00",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
