language: python
python: '2.7'
script: py.test
deploy:
  provider: pypi
  skip_upload_docs: true
  user: iml
  password:
    secure: iQ657CWtGaweT0I+zD379ahWWTWQTAtOX59c9EGDDPQ2GvIRnL0qR9NhRKf1kFx0rja1U0rumGio6B6mVU4TY19KHcGa6/6VAZcklXeJ1NmkdDahDZxKchvv9zovQuqf1LaMHhbqkCKo8csOeCToL+lF7QeOKjBOvzUB/a2i+zSREkpLlT7DrHIwyRLZe4626g5ZPz6m1C7VCG599MEnpe6aqgcj04Vcn09cP88GleHWL98OIhyuuJanaRdxApfYih4ZCFSPwYccH6RLSkevYsPjjiGtfXIHLaDceL9m4V0qzXtQ5F0f2FgVNkArRkJHE4RXliqsOEOG/AKiHZaLxYqJHuljguAkT3D3mAb29MbkL07SBGwV4eHtW6m3YKPHR1G+ZzCmLHXio9FVGfwG4rRIruOBlnpBral7umFuol14bEsmSgoFFQfG6ouq90M3hy81SDLrJXeb60hXsLlkxEXC6wERL9wgFeiT0sbVdqNI94YQb31/dlVfL/upRbN5qpTTE9nnnnIWyCC+x6yBy4H6KmhKZxkejTvmofzLlvx3t7ySVx9Z6GUEe7XLBsGR2Gak/2X6X+zYOwbysnCXInQlltJrWy0BUFBS4Oz0WhQrP/TDhzU4cTYytVnxNCtGJXG/UA3dg7ZEfnG1QuiY8FlI+zdpZGFoUdurSMq4Tgo=
  on:
    tags: true
