# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/kinematics/AngularVelocitiesCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.kinematics import AngularVelocities_pb2 as rst_dot_kinematics_dot_AngularVelocities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/kinematics/AngularVelocitiesCollection.proto',
  package='rst.kinematics',
  syntax='proto2',
  serialized_pb=_b('\n0rst/kinematics/AngularVelocitiesCollection.proto\x12\x0erst.kinematics\x1a&rst/kinematics/AngularVelocities.proto\"Q\n\x1b\x41ngularVelocitiesCollection\x12\x32\n\x07\x65lement\x18\x01 \x03(\x0b\x32!.rst.kinematics.AngularVelocitiesB!B\x1f\x41ngularVelocitiesCollectionType')
  ,
  dependencies=[rst_dot_kinematics_dot_AngularVelocities__pb2.DESCRIPTOR,])




_ANGULARVELOCITIESCOLLECTION = _descriptor.Descriptor(
  name='AngularVelocitiesCollection',
  full_name='rst.kinematics.AngularVelocitiesCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.kinematics.AngularVelocitiesCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=189,
)

_ANGULARVELOCITIESCOLLECTION.fields_by_name['element'].message_type = rst_dot_kinematics_dot_AngularVelocities__pb2._ANGULARVELOCITIES
DESCRIPTOR.message_types_by_name['AngularVelocitiesCollection'] = _ANGULARVELOCITIESCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AngularVelocitiesCollection = _reflection.GeneratedProtocolMessageType('AngularVelocitiesCollection', (_message.Message,), dict(
  DESCRIPTOR = _ANGULARVELOCITIESCOLLECTION,
  __module__ = 'rst.kinematics.AngularVelocitiesCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.kinematics.AngularVelocitiesCollection)
  ))
_sym_db.RegisterMessage(AngularVelocitiesCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\037AngularVelocitiesCollectionType'))
# @@protoc_insertion_point(module_scope)
