# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rst/kinematics/TwistCollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rst.kinematics import Twist_pb2 as rst_dot_kinematics_dot_Twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rst/kinematics/TwistCollection.proto',
  package='rst.kinematics',
  syntax='proto2',
  serialized_pb=_b('\n$rst/kinematics/TwistCollection.proto\x12\x0erst.kinematics\x1a\x1arst/kinematics/Twist.proto\"9\n\x0fTwistCollection\x12&\n\x07\x65lement\x18\x01 \x03(\x0b\x32\x15.rst.kinematics.TwistB\x15\x42\x13TwistCollectionType')
  ,
  dependencies=[rst_dot_kinematics_dot_Twist__pb2.DESCRIPTOR,])




_TWISTCOLLECTION = _descriptor.Descriptor(
  name='TwistCollection',
  full_name='rst.kinematics.TwistCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='rst.kinematics.TwistCollection.element', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=141,
)

_TWISTCOLLECTION.fields_by_name['element'].message_type = rst_dot_kinematics_dot_Twist__pb2._TWIST
DESCRIPTOR.message_types_by_name['TwistCollection'] = _TWISTCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwistCollection = _reflection.GeneratedProtocolMessageType('TwistCollection', (_message.Message,), dict(
  DESCRIPTOR = _TWISTCOLLECTION,
  __module__ = 'rst.kinematics.TwistCollection_pb2'
  # @@protoc_insertion_point(class_scope:rst.kinematics.TwistCollection)
  ))
_sym_db.RegisterMessage(TwistCollection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\023TwistCollectionType'))
# @@protoc_insertion_point(module_scope)
