cache: pip

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis
  - pip install codecov
  - pip install codeclimate-test-reporter

script:
  - tox

after_success:
  - codecov
  - codeclimate-test-reporter

deploy:
  provider: pypi
  user: laslabs
  password:
    secure: PYQP4YLCrX5Baj8nk+ofTbStEChvQEU4giV1RWhU0ZHcTHlhheKYTkZCI3jmtLI7nL6EWZcJ0IDXAbBy+Q0QhV6zqpKptYnlaG1COzDN02eCVdZq59/Zn6lcCvRvcxp6FqXCvCnR9hN5uyXHtYUKvWGQO7uttf3WVmIVTDu+XBMYJJ3dt2v0wCH/H10beQ8bzRYNn0ynxSgBorXZviKi+RtfpxoBmz/XpmLV+0lSNcbxAR+ayjt4QPMXsTX5E0+tMBh7Vpv6KdpJkBLydLAPpJ7BHEnqP13ktEvTeBRAwnYf+dVR02T26SdiuJR2D6bJglm6x/m/qfLj9OeeiFStcpWSnV6IUNCoeIkZYH/KsINKBbONEez62MnnzAld78DWv2L+Xx1O/99R9F4IHEud43FZHSgfD+P5TTGxsQew0NjM22QDUJRR3FPsl4tEi986LrgltU5+f5bndP2uxjmMGZREtzwgtmJHrWamYEVLjQAppFBKtcavBXSSp5ioVg5FJgVZVh4Al9MMkIjPNzTmo6YYN/bz8wyU5LnAscyWLy7CtKS7KqD7OL8QwNx/dBPMQr0nZ3ce0es6jjZyd5SDNXPQ4SSKsTN7XYhvOO2d1asIHzg10qXy3r2w9jZA8jLVEHB0UgH8HcQuCSNf+rSzsHpKYNTnFrvpJWrxa1mAc58=
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
  on:
    repo: OCA/oca-decorators
    branch: master
    tags: true

