# AppVeyor CI
# https://www.appveyor.com/docs

environment:
  matrix:
    # For Python versions available on AppVeyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

install:
    # Twisted requires pywin32 on Windows in order to spawn processes.
    - "%PYTHON%\\python.exe -m pip install pypiwin32 pipenv"
    - "%PYTHON%\\python.exe -m pipenv install --dev --system"

build: false

test_script:
    - "%PYTHON%\\python.exe -m twisted.trial --reporter=text --rterrors txrwlock"

on_failure:
    # Store _trial_temp directory as artifact on build failure.
    # See <https://www.appveyor.com/docs/packaging-artifacts#pushing-artifacts-from-scripts>
    - ps: |
            $root = Resolve-Path _trial_temp;
            [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % {
                Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName trial-log
              }
