
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-19T23:54:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dd2d0c29df0bd7b26f93b16dacd97cacff361b3",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
