
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6810435479a79a3c783ddcf7efadaa98125b321a",
 "version": "7.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
