__version__ = "0.4.14"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = u'(HEAD detached at v0.4.14)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd9fbe1eb8beeab7a597c6a2ce2277f0760e795ce'
__git_head_subject__ = u'Finished Release v0.4.14'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-11-15 16:30:53'
