
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-17T16:10:49-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "10f7cba2a5328994cb9e07f06c06e36e39c5f527",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
