language: python
sudo: false

notifications:
  email: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"

env:
  - WITH_SHAPELY=1
  - WITH_SHAPELY=0

addons:
  apt:
    packages:
      - libgeos-dev
      - pandoc

install:
  - if [ $WITH_SHAPELY -eq 1 ]; then
      pip install numpy "shapely[vectorized]>=1.6b4" ;
    fi
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python -c 'import geopip; print(geopip._geopip.SHAPELY_AVAILABLE)'

script: PYTHONPATH=$PWD pipenv run pytest

after_success:
  - coveralls

before_deploy:
  - git stash --all
  - pandoc --from=markdown --to=rst --output=README.rst README.md

deploy:
  provider: pypi
  user: tammoippen
  skip_cleanup: true
  password:
    secure: l+dWOwBywp+TyFgPEoJBhR+I44E4AMCgjxIaEd6AD0bv2yPeJQGUX/oPiOlQVbtcjqBbESZ6dZA0FVYcO7OCP+uK768S18GaTketFz7EByrSJqrjOt5Ka4TCgAPfo5d/0pHeEGQUqjHWNsP9V0WSx4UFIBv0s7bs8uLduJrGDdyjpH/Ki/l5Arl+H8gygdFRzW4oIhF0u/7AjQ1VKN9WZV9HYB6D+SF0rWP2bZvqFMvBBfwagCbwLsD2QPGJz4nFwBoL5bY2YrEEQ6TrtQbyqL65IS9wYfrEo2c/miC7nCS2p2pI9jRqnMENREvKeJRx2Nck0ZKxdW1R63odvU5I4+OzG5BKo/Q7GHma1jCXn8Qj/RPYIEDIiCmgeTXElq13409J2TA34dpIM32hfXt4SmHzACwPvy5tr1FMGIYrFqVCl9J4Z3kDRkIvZP9EYhFrOy11hVCXNEUv79qk8YswmWhgs/tsB9IiriZD9CewtpbmiEvok//X0ExeykTe93t6D27ehDPwDm4j/FisTLv6i2PRXySqWnE0+Q6cCoAmeDG5GyJ4KKzbPE9sdqQoyrh1bbSGfRfVGdzVKyaHO1Y3y1U5raXEuZ4nNJ0XWIWiwgedB4YFsF/7ZWN7MbGZ7QXxifXEPXsrEMVOofyx349mhIJP1ibCh/Zh+QTrYldXNmw=
  on:
    branch: master
    tags: true
    python: "3.6"
    condition: $WITH_SHAPELY -eq 1
