
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-11-11T18:27:39-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "138965b9a66ea51484aa2d84405fc32a92cb6bcd",
 "version": "3.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
