language: python
python:
  - '3.6'
script:
  - pytest test
deploy:
  provider: pypi
  user: '{pypi_username}'
  password: mypassword 
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
    tags: true
